### ISSUE TITLE
OK & Next as default

### ISSUE THREAD

**Issue by bijaySussol** [msupply-foundation/open-msupply#1730]
## What went wrong? 😲

Nothing wrong with how the OK & Next works i.e using Mouse, but would be much much quicker on entering if user can just use enter key from Keyboard where OK & Next is set as a default, bring speedy entry and avoid less using of Mouse. I wonder...
Same as OG

## Expected behaviour 🤔

Using Enter from Keyboard if OK & Next trigger or takes to the next creation of records or viewing etc.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a new location
2. Use Keyboard `Enter`
4. Does not take to next window to create

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [x] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

**Comment by CarlosNZ** [comment]
I'm not particularly clear about this one. Which forms are you thinking of specifically, or do you mean all forms?

Because for most forms, we wouldn't want the "Enter" key to click Okay or Okay & Next, because how is the app supposed to know if the user has finished entering all the data they intended? "Enter" for "Okay" makes sense when there's only one field, or a dialogue with different options, but I'm not sure how it would be useful on a more complex form. As a user, if I pressed Enter on a form, I'd expect it to just go the next line (or something equivalent), not submit my form.

**Comment by bijaySussol** [comment]
> Which forms are you thinking of specifically, or do you mean all forms?

Maybe, When adding lines to Outbound and Inbound would be a good start on top of my head as this probably be the mostly been used.

**Comment by roxy-dao** [comment]
Closing as the `enter` button does now default to `Ok & Next`
