### ISSUE TITLE
Export reports to excel (requirements)

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#2059]
TSS compliance 

Being able to export to excel

Jobcode: PG23OMD

**Comment by clemens-msupply** [comment]
Also see https://github.com/openmsupply/open-msupply/issues/705

Some ideas for using existing Tera infrastructure for excel exports:
Using Tera to edit an excel file (not csv) probably doesn't work (?) but we could have our own intermediate data representation which can be generated using a Tera template.
This intermediate repesentation must be powerful enough to describe which data goes at which position in the final excel output file.

For example, workflow could be like:
1) The report designer can define a template excel file which is used as a template for the final excel file. Similar to an html template.

2) Then use existing report infrastructure to generate the intermediate representation file, e.g. as json like:
```ts
{
  tables: [
     {
        dataSheet: "Sheet2",
        location: { row: 10, column: 5 },
        rows: [
            ["Data", "values", "for", "every", "column"],
            ["Row2", "...", "...", "...", "..."]
        ]
     },
     {
        dataSheet: "Sheet3",
        location: { row: 1, column: 1 },
        rows: [
            ["More", "data", "at different location", 1, false, ...]
        ]
     }
  ]
}
```
I.e. describe which rows go at which position in an output excel file. This could be further extended by including styles...

3) Use an existing Rust crate to fill the intermediate representaion into the tempalate excel file, i.e. fill the template with data.

**Comment by clemens-msupply** [comment]
@jmbrunskill do you have an opinion on it?

**Comment by clemens-msupply** [comment]
An alternative would be to not support custom styling at and just use Tera to export to CSV with the server side option to transform the CSV to an Excel file (like we currently do with HTML and PDF).

**Comment by andreievg** [comment]
I am not sure what the full list of requirements is for the excel reports, it maybe a bit of process to get all the stakeholders to participate in the requirement gathering.

I only had a quick chat about this with @craigdrown, in which csv format was considered limited, and we should allow formulas etc..

I don't think we need to format the excel 'on the go', the template can define the formatting.

Although we shouldn't need to define template different from HTML/PDF to excel, maybe this would be too hard and we just need to 'share' the data component of those templates and have different definitions for display component of the template ? (Sorry that doesn't sounds like a requirement, i think the requirement should read something like "as much as possible, consolidate template definition for HTML/PDF and Excel").

I haven't come across anyone asking for multi sheet reports.

I think the first part of this issue would be research into what is possible, and compare that to the requirements, at which point we can balance out effort of dev/config vs requirements to see how much time we have for it, i.e.:

* We can use separate tools for Excel and HTML/PDF, which would be quicker to dev but require a lot of configurations (we want to minimise support/deployment spending so probably won't work)
* Can use Excel first templating and the convert to PDF (this would require some Excel rendering and converting .bin, which most likely won't be available on mobile)
* Can make our own templating engine from scratch for both Excel and HTML/PDF (that will likely be way too much work, we wouldn't have budget for this)

I am sure there is an option that has the right balance for us though

**Comment by jmbrunskill** [comment]
> @jmbrunskill do you have an opinion on it?

I sort of have opinions, but like Andrei pointed out would like to understand more requirements (and the current reporting infra) better.

If the goal is to simply meet the TSS requirements I'm tempted to suggest something built with the specific requirements for TSS, rather than a generic reporting infrastructure. The issue with that would be fragmentation of course but I feel like there's probably a lot of standardisation that can and perhaps should be done with reporting.

I like the idea of being able to write SQL rather than just using Graphql, which has it's own challenges with different database flavours but mostly I think it could work...

> Using Tera to edit an Excel file (not csv) probably doesn't work (?), but we could have our own intermediate data representation which can be generated using a Tera template.

This sound pretty scary to me, but I'm not sure if I understand the idea correctly. Are you suggesting that the tera template generates json? 

That feels like it's going to error prone and difficult to implement but happy to be proven wrong! I think the intermediate representation idea in general makes sense though. e.g. the results of an SQL query are a table for example.

Do we have a Job code and a Budget for this?

**Comment by clemens-msupply** [comment]
> I like the idea of being able to write SQL rather than just using Graphql, which has it's own challenges with different database flavours but mostly I think it could work...

Main reason for GraphQL is that we already have permission in place, e.g. if you don't have the correct API permissions you can't do the report. But yes SQL would be nicer than Graphql, I already ran into some limitations for some program reports...

> That feels like it's going to error prone and difficult to implement but happy to be proven wrong! I think the intermediate representation idea in general makes sense though. e.g. the results of an SQL query are a table for example.

Agree, not very simple/elegant. Andrei, Mark and I had a short chat about this issue. One idea that popped up was to convert HTML to Excel. For example, we could use the existing reports and extract the HTML tables from it and then put them into an Excel file. If needed we can annotate the HTML tags with Excel specific attributes or classes, e.g. for styling, positioning or formulas. Depending on the use-case this would allow us to only create a single report which can be exported to HTML, PDF and Excel.

**Comment by Gwalior-84** [comment]
Reports are a HUGE issue.  I understand the Agile / MVP philosophy, but this is one area where I think it doesn't strictly apply.  We need to carefully think about the big picture of reporting requirements, and make sure that any MVPs are not dead-ends where we will then have to start again (bitter Carbon experience speaking?)

We need to ensure that we have inputs from consultants experienced with customer demand for reports, e.g. @craigdrown @GaryWilletts @ujwalSussol @Pauline-mSupply 

The main issues I see is that there is a huge range of report customisations that customers ask for - just have a look at the range that we have made and continue to support for existing customers using Legacy mSupply.  I can see no reason why the demand for this will diminish, and if Open mSupply can't somehow meet this demand, then that will be a show-stopper.  This 'somehow' needs to be possible with minimal TMF dev input - which is, I believe, the case currently with Legacy mSupply.

Having said that, I think we can see a couple of classes of user stories involving reports, and the reporting solutions might be quite different.  One 'reporting' tool may struggle to cover them all:

- As a store operator I need to generate the standard 'logistics' paperwork associated with managing stock:  POs, GRs, SIs, Pick lists, CIs, Waybills, stocktake sheets, etc. etc.  These are always produced in hard copy (PDF is good) and printed out.  Some of them will need a human to sign them and important ones will need an organisational stamp.  BTW, I've talked to PNG about building in the logged-in user's signature to the forms, but they have not actually been interested.
- As a manager / consultant (very influential), I need to generate spreadsheets containing large amounts of data that I will analyse.  These will only ever be generated in Excel, but need to be Excel Filter and Pivot-table friendly (unlike many Legacy mSupply Excel reports).
- As a manager / consultant, I need to generate a printed report (PDF) that I will hand to the boss / management committee.  This report will analyse data and summarise the results in an intelligent fashion.  For example, we have a current request for a report that will produce, for each of 7 major stores in country and for all 428 'Essential' items (has the Essential Drug flag):
  - A list, broken down by therapeutic category (Item Category 1, 1 page per category) of items, highlighting those items that are
    - Overstocked (stock will expire) with the suggested inter-store transfers if that will prevent expiry, and the predicted value of stock that will be discarded
    - Understocked with the recommended amounts to procure immediately (lead time = 3 months) and for longer term (lead time = 12 months) and the values thereof.

**Comment by craigdrown** [comment]
⬆️ is a good summary of the reports we need, thanks @Gwalior-84 
I don't see any huge problems with HTML-to-Excel - it can be simple to start with, and expand capabilities over time. 
It could also be expanded to support Excel templates at a later date, which saves a lot of time with formatting report headers in other languages.
I did have one thought- it would be nice for Tera templates to support internationalisation- is there a way to do that on the server at the moment? (Angola wanting us to convert *all* mSupply reports to Portuguese at the moment- big job)

**Comment by Gwalior-84** [comment]
Actually, I suggest that as a general approach, until we have Open mSupply as the central server (a good year or two yet?), Legacy mSupply can serve the needs of managers and consultants.  In this case, Open mSupply reporting can safely focus on the needs of the store operator.

The exception to this general approach might be special things like the Programmes Module that we have developed in Open mSupply (which might be what is driving this issue @clemens-msupply ?)  All the additional data is, of course, being synced to the Legacy mSupply central server.  But we have no current capability for generating reports on this data in Legacy mSupply.  We either develop the report in Legacy mSupply from scratch, and then develop it again in Open mSupply later, or jump to the latter immediately.

**Comment by Pauline-mSupply** [comment]
@Gwalior-84 I agree that this is a rabbit hole that looks easy at first but is not. My approach to reports is the following : 

### Standard logistics paperwork for store manager : mSupply customised report. 
-  Usually, we are asked to reproduce an existing document so we cannot simply use a template 
- The customisation would be for headers, signature, names, level of details in stock data. 
- It would still require someone to create the JSON file. 

### Analytical spreadsheets for managers / consultants : mSupply customised report. 
-  I have noticed that some consultants actually prefer raw data so that they can play with it and decide the level of details they want, so I would use an existing customised report with as much raw data as possible.

### Anything more sophisticated / complicated :
  - Orient client towards Grafana.
  - It doesn't depend on a version of the software, so it can be modified easily. 
  - Deployments and reports are no longer depending on each other (if a report is not working halfway through deployments, we don't need to reinstall a new version
  - Export to excel is an existing button. 
  - Users outside mSupply (like MOH Cabinet members) can access it if we create them an account.
  - The main issue is that the interface is not translated yet

**Comment by clemens-msupply** [comment]
Some brief summary:
- PDF reports (currently supported)
- Large Excel Reports. Possible problem is that our GraphQL APIs have pagination limits.
- Custom logic to transform data coming from the API. For example, group by category, overstocked, understocked items, etc. (Tera can do data processing to some degree)
- Localization (We could pass a localization object with predefined labels to the Tera templates... Translations could probably be taken from UI translations...)
- Dashboard reports and how they play together with reports that run on the local site. Where is the line between buildin reports and dashboard reports? (Would we actually fulfill TSS requirements using just dashboard reports?)
- Admins or power user must be able to create or edit reports.
- Able to connect to external analytic tools (already possible through the dashboard database)

Required Excel features:
- Formulas to calculate sums
- Merged cells
- Multiple work sheets
- Styling
- Pivot tables friendly

@Gwalior-84:
- This issue was not programs specific mainly driven by TSS requirements
- What is an example for a pivot table unfriendly table?
- What where the limitations/problems with Carbone?

**Comment by Gwalior-84** [comment]
> * What is an example for a pivot table unfriendly table?

We had a general programme over several years to fix these:  [Reports need to show store, be filter / pivot table friendly and export to Excel.](https://github.com/openmsupply/msupply/issues/3424).  A specific example, where the default report is not pivot table or filter friendly:  [Requisition > Group by item report](https://github.com/openmsupply/msupply/issues/6301).

**Comment by Gwalior-84** [comment]
> * What where the limitations/problems with Carbone?

I don't know.  Can you please enlighten us @GaryWilletts?

**Comment by GaryWilletts** [comment]
> > * What where the limitations/problems with Carbone?
> 
> I don't know. Can you please enlighten us @GaryWilletts?

It had limited functionality for generating generic reports at the time: some more complex things were very hard or impossible to do. Not completely free, some features are paid but we managed to get by with the free stuff. Might have improved now, it was a couple of years ago we used it.

**Comment by clemens-msupply** [comment]
The implementation is tracked in this issue: https://github.com/msupply-foundation/open-msupply/issues/2868
