### ISSUE TITLE
Cold Chain / Monitoring - Multiple

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#2481]
## Is your feature request related to a problem? Please describe 👀

N/A

## Describe the solution you'd like 🎁

- [ ] 1. add "number of breaches" scorecard under the temp chart

Home > Cold Chain > Monitoring > tab: Chart 

Add 2 scorecards below existing chart that would display number of breaches recorded in the selected time range / sensors / location / etc...:

- number of hot breach(es), acknowledged or not
- number of cold breach(es), acknowledged or not

or Adam's suggestion below: 

> Nice Richard!
> 
> I'm actually wondering if it might be better to have scorecards for '% stored safe' vs '% stored unsafe' instead of # breaches - as you could have 1 really long breach which would be worse than a few really short breaches?

make sure to let @anisha-msupply know if we proceed with this feature. 

- [ ] 2. Filters: Date/Time "Quick" Ranges: 

Would be nice to have some quick ranges (last 30 days, last 90 days). Sounds like the most common reporting period for cold chain data is 7 days (weekly) and 30 days (monthly) FYI

- [x] 3. Chart: Suggested by @adamdewey:` Would it be possible to anchor a bold 2° and 8° on the thresholds?`

- [ ] 4. Location filter: should be a drop-down list ?

### Describe alternatives you've considered 💭

N/A

### Additional context 💌

N/A

### Moneyworks Jobcode 🧰

OMS:COLC

**Comment by adamdewey** [comment]
Nice Richard! 

I'm actually wondering if it might be better to have scorecards for '% stored safe' vs '% stored unsafe' instead of # breaches - as you could have 1 really long breach which would be worse than a few really short breaches?

**Comment by mark-prins** [comment]
3. is fixed with #2484 😃

**Comment by mark-prins** [comment]
Another suggestion is that the sensor filter should also be a drop down list. Any interest in doing that @richardmoizeau @adamdewey?

**Comment by adamdewey** [comment]
Soz, haven't had a chance to play with it yet, so unsure how the current filter behaves!

**Comment by richardmoizeau** [comment]
> Another suggestion is that the sensor filter should also be a drop down list. Any interest in doing that @richardmoizeau @adamdewey?

Yes I think that would make sense. I think it's likely tha

**Comment by mark-prins** [comment]
The filters between log and chart could remain - there are different filtering options on breach view, though I don't think it would be a problem retaining them. It's a nice idea, thanks.

**Comment by adamdewey** [comment]
Yeah I agree with Richard, I think most users will want to look per CCE mainly - and it would be better to show them a dropdown so they don't need to remember the names of everything for searching.

**Comment by DhanyaHerath** [comment]
@richardmoizeau from triage: can you move this into the design doc to note for phase 2? We can then close this issue for now

**Comment by adamdewey** [comment]
@DhanyaHerath, @richardmoizeau  - is there a design doc for phase 2? 

I have a ton of things I'm noticing as I'm starting to use omSupply temperature monitoring - would be good to be able to slot them into some kind of priority order 

I'm trying to capture everything cold chain-related into one place so people aren't having to reference multiple places. 

For now I think we have: 

- Trello
- GitHub single issues
- GitHub combined issues (like this one)
- At least one Google Doc containing multiple issues (e.g. https://docs.google.com/document/d/1py8Bc8Z0o5NsGQwX9XBNEIdeyPZWzNQ_8zLh8WdM24w/edit)
- Design Google docs
- Figma diagrams
- Probably more than I'm not aware of

For me, I use the Trello board as the source of truth for all cold-chain stuff, so that things don't disappear into the ether. 

I'll transfer the comments in this issue to Trello cards and we can close this.

How about we then start to build up a CC phase 2 by starting to draw things in from the Trello board?

**Comment by adamdewey** [comment]
Ok cool, captured here: 

- https://trello.com/c/PxLu0RfA/177-temperature-chart-scorecards
- https://trello.com/c/8jArvD9u/178-temperature-chart-quick-date-ranges
- https://trello.com/c/MIT4smla/179-temperature-monitoring-drop-downs-for-filters
- https://trello.com/c/23k3xqDq/180-temperature-monitoring-persist-filters
