### ISSUE TITLE
High CPU when loading full patient list (sqlite)

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#2505]
Moved from #2504 
The remote server seems to use quite a lot of cpu when loading the full patient list (sqlite). Profile what is happening and how it can be improved. (This can be moved into another issues)

- [ ] Use a profiler such as callgrind and identify the code that is called most often when doing a query to the `patients` endpoint (with patient document data)

**Comment by clemens-msupply** [comment]
Some idea what to look at:

1) Durring sync, integration of a large data takes a long time. Figure out which part takes so long, e.g. is it programs data?

2) Querying `documents()` data is relatively slow and has a large "base cost" independent from the pagination count, e.g. querying 10 document takes almost as long as querying 1000 docs. For example,

```graphql
query MyQuery {
  documents(storeId: "", page: {first: 10}) {
    ... on DocumentConnector {
      nodes {
        data
        name
      }
    }
  }
}
```

Questions:
- [ ] benchmark the folling configurations in various configurations: `first = 10`, `first = 1000`, `nodes: { name }`, `nodes: {name data}`
- [ ] Does the `latest_document` VIEW makes the query slow? is it faster to query directly query the raw `document` table?
- [ ] Or is it the fetching of the json data? i.e. is it faster when doing a direct sqlite query without fetching the data?

3) Querying document for program enrolments.

This query is quite slow. For example, much slower than fetching 1000 documents directly.

``` graphql
query MyQuery {
  programEnrolments(storeId: "") {
    ... on ProgramEnrolmentConnector {
      nodes {
        document {
          data
        }
      }
    }
  }
}
```
Questions:
- [ ] Is it maybe the document loader which makes it slow? For example, compare it to a direct sqlite JOIN query that returns the same data.

**Comment by fergie-nz** [comment]
I can see that querying documents as a node from patients or program_enrolments takes a long time.

Interestingly the query for both documents and program_enrolments (as nodes) on a patients query takes longer than the sum of a patients + document node query and patients + program_enrolment node query. 
The combined query can take more than 3 seconds on my machine.

I also see that the program_enrolment node for patients doesn't use a loader. I wonder if there is a reason for that structure?

**Comment by clemens-msupply** [comment]
Implementing a loader for program_enrolments is a bit tricky because it has all these filter parameters. A loader batches up similar requests and then does an optimized query to fetch the whole batch. Because of the different filter parameters this isn't easily possible, first because how do you hash a filter and secondly because how do you combine all the filters into a single sql statement?...

A loader has a time offset before it queries data. For example, it you do a request it waits ~300ms (just making this value up) to wait for more requests to batch them all up into a single sql statement. If this time elapsed (or if there where more than 1000 other request before these 300ms elapsed) it does a single sql query to fetch all the data for all the requests. So if you are the only user you always have to wait 300ms before you get something back from the loader...

What you are seeing might be an effect of how the loaders works. A bit of guessing... Also important to know is that the DB requests are not async so if graphql does an DB call it blocks the current api handler thread. The following could happen then:
- For each patient you request the document through the loader and you request the program enrolment
- The document request get batched and doesn't block the current thread
- The program_enrolment request is done immediately and blocks the thread
- Thus it can happen that only a handful of document requests get batched within the 300ms because the thread was busy fetching program enrolments
- Thus more DB calls are needed to get all documents (would this make it that much slower? maybe, e.g. if there is a base cost to calculate the `latest_document` view for every DB call.)

What is the times for the separate queries?

Good finding!

**Comment by fergie-nz** [comment]
Thank you for the very detailed reply, @clemens-msupply! That is very helpful for my understanding.

Your guess matches what I was seeing of multiple (maybe 15) document calls when I queried both program_enrolments and documents through a patient call. (along with many program enrolment queries)

Average times were:
Only patient data: 56ms
Patient + document: 518ms
Patient + enrolment: 1600ms
Patient + document + enrolment: 3920ms

**Comment by fergie-nz** [comment]
No further action required just now :)

**Comment by clemens-msupply** [comment]
Thanks Ferg! I think we have a pretty good overview where the pain points are now and if they become an issue we can address them. For the currrent usage the current graphql queries work fine now and I think we can close this issue.
