### ISSUE TITLE
Getting redirected to login page while being active

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#2509]
While using the programs modules I got logged out frequently while using the system. @mark-prins don't we go to the logout page if there was an error, e.g. a network error? I have the feeling that this is what happened.

Is there a way around it? e.g. just show an error but stay on the same page? and only got to the login page when the token expired?

- [ ] Figure out what exactly went wrong when being redirected to the login page
- [ ] Provide smother user experience

**Comment by CarlosNZ** [comment]
Perhaps this might fix it? https://github.com/msupply-foundation/open-msupply/pull/2485

**Comment by mark-prins** [comment]
> @mark-prins don't we go to the logout page if there was an error, e.g. a network error?

There was an issue with the standard dialog which wasn't actually logging users out, but had the default action redirecting to login - if the implementing area didn't specify an action then the user was always directed to the login screen.

That issue is fixed, so I'm hopeful that what you're experiencing is the issue that Carl has fixed. Would it be ok to close this issue and reopen if you see it happen again? Or would you rather keep this open and retest?

**Comment by clemens-msupply** [comment]
This seems to still be an issue and need further investigation

**Comment by clemens-msupply** [comment]
Don't seem to be an issue anymore? can be reopend when it pops up again...
