### ISSUE TITLE
Can't close a patient without  first editing something

### ISSUE THREAD

**Issue by adrianwb** [msupply-foundation/open-msupply#2541]
## What went wrong? 😲
 

![image](https://github.com/msupply-foundation/open-msupply/assets/6196269/1e854473-a1aa-4040-b1b1-9f0290f2c2d0)

The Cancel button is disabled until you edit something => you can't just close it. I know that the browser back button also works, but I don't think we should be relying on that in a "proper" application...

## Expected behaviour 🤔

Should be able to close the patient without editing it first!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Patients
2. Click on a patient record

## Your environment 🌱

 - Version: 1.5.0
 - Platform:
   - browser (Opera on Windows 11)
   - server (Windows)

**Comment by roxy-dao** [comment]
Do we need the cancel button here? We have a notification that pops up when the user is editing and tries to navigate away, so the cancel button feels a bit pointless? 🤔

**Comment by CouldBeFree** [comment]
I can fix this issue

**Comment by CouldBeFree** [comment]
What data should be entered in order to use this app for developing?
![compressed](https://github.com/msupply-foundation/open-msupply/assets/25415541/89f5f622-3616-4a58-ae3c-16607f96e7f6)

**Comment by CarlosNZ** [comment]
I *think* this is due to the fact that just by opening a patient document, some fields are filled with an empty object, which we have an issue for here: https://github.com/msupply-foundation/open-msupply/issues/2543

**Comment by Chris-Petty** [comment]
@CouldBeFree Great! I'm glad that worked at least getting you logged in at all 😁. The reason you get that response is for each user is that you usually need to login at least once with a connection to the central server (which you don't have sorry!). `admin` probably works because I had used that user when creating the export. I thought maybe the export process would have pinged the central server to preload the other users, why else specify all of the users in the CLI params 😁.

For dispensary, first some context. In open mSupply we have _stores_ - these represent different functional areas in a facility that _store_ and manage stock. e.g. a hospital might have a inwards/outwards goods store to supply the overall hospital, and separate stores for each pharmacy throughout the hospital.

With that said, can you check what store you've logged into? For me on that datafile it looks like this at the bottom of the page: 
![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/081cc7b6-7910-40f9-95e7-623c24a3a3c1)

You'll need to make sure you select Waikato Pharmacy. Hopefully that gets you a step closer 😃

**Comment by CouldBeFree** [comment]
@Chris-Petty thank you for your support. `Dispensary` tab is now available, so now i am ready to resolve this issue

**Comment by CouldBeFree** [comment]
I am trying to run `yarn pre-commit-lint` and I run into the error `Error: Cannot find module '@nx/nx-darwin-arm64'`.
When in try to run `yarn add -W @nx/nx-darwin-arm64` I fall into this error `@nx/nx-darwin-arm64@17.1.3: The CPU architecture "x64" is incompatible with this module.`
Is there some way i can fix this issue, because i can't commit my changes?

**Comment by Chris-Petty** [comment]
Hmm weird. Can you confirm where you're running your changes and what your environment is? I assume you've been able to get dev working and hot reloading your changes and what not?

**Comment by regotaina** [comment]
'Cancel' button works now on RC3. Passed the test 👍
