### ISSUE TITLE
[Test] - mSupply and omSupply on the same device syncing to same site

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#2588]
A use case triggered by a question from @regotaina.

Can user by accident, set up omSupply and mSupply mobile on tablet (or maybe even desktop version on the same PC), and try configure it for the same 'site', would hardwareId match ? And both instances would sync to the same site ?

This would need to be tested/validated

**Comment by nisha-dangol** [comment]
@andreievg : The answer to that above question would be No! 
I set up one of the sites in the oms-tablet, and then tried to initialise the same site in the mobile app in that very same tablet. It didn't let me saying `Site hardware ID does not match` which looks correct as well. (since in cloud, that site is registered as Open mSupply Mobile as device type!)

**Comment by DhanyaHerath** [comment]
Can we close @andreievg?

**Comment by roxy-dao** [comment]
Bumping. Can this be closed?

**Comment by andreievg** [comment]
I am happy to close if we do a test on desktop for this (I can see this as a use case happing during migration of mSupply to omSupply sites, and having quite bad impact).

@nisha-dangol thanks for your test on tablet, do you mind having a quick test for desktop

**Comment by roxy-dao** [comment]
Thanks Nisha
