### ISSUE TITLE
Android in kiosk mode back button issue

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2611]
## What went wrong? 😲
 
We are facing an issue when we click back button multiple times our open msupply apps get stuck and no way to restart it so we have to restart the tablet completely… and users are very good in pressing back button multiple times. 

This case is found while tablets are in kiosk mode but in normal tablets it’s working perfectly… any advice on it is it something with kiosk or our apps?

## Expected behaviour 🤔
Back button shouldn't cause an issue. what's up with kiosk mode?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by mark-prins** [comment]
Tested with current version: unable to recreate the 'getting stuck' aspect, however the back navigation isn't doing anything, rather the app closes on first pressing the back button

**Comment by nisha-dangol** [comment]
Hi @mark-prins ! Few questions on the android-back button:
1. Wondering if this back button should not directly logout the user? I think the logout modal should show before that. What say? [Recording reference](https://github.com/msupply-foundation/open-msupply/assets/59193490/1a592241-97de-4a98-9282-bbab5cbc1095)
2. And, when you create new shipment and open add item, the back button should throw back to previous, shipment window (closing only `Add item` modal instead of landing back to Dashboard/home page?)
3.

**Comment by mark-prins** [comment]
@nisha-dangol - that would be better.. but that's really hard!
Will see if we have any control over the behaviour, I think maybe we could do #1 but the second one, not sure if that's possible. Will need to investigate - I've made a new issue (#3209) to see what we can do.
