### ISSUE TITLE
Edit Master Lists

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#269]
Add the ability to edit master lists
- [ ] add and remove items
- [ ] edit comment
- [ ] edit name
- [ ] create lists
- [ ] delete lists

**Comment by andreievg** [comment]
After creating a test `upsert` end point on central server (for integration tests), I realised we can quite easily transition to central data configurations via omSupply (existing layers actually allow for this to be done and updated to use database vs end point in a nice manner).

* Central server defines a site as central data controller
   * The upsert end point is available to that site (also delete end point)
   * Query end point is also made (in the same generic fashion as upsert end point
* if omSupply site is central data controller, UI present central data configuration
   * Back end queries for records through provided query end point and mutates them with the upsert/delete end point 
* After editing, we do need to sync omSupply site to see new master lists

On back end we use existing layers, repository layer would use API vs Database (but would be made to look and feel like it's a database layer), we swap repository layer when needed.

I am kind of exiting about this (seems like a good way to transition), but we do have to be mindful how we edit central data, I think for master lists it should be super easy, they are simple.

**Comment by Chris-Petty** [comment]
> After creating a test `upsert` end point on central server (for integration tests), I realised we can quite easily transition to central data configurations via omSupply (existing layers actually allow for this to be done and updated to use database vs end point in a nice manner).
> 
> * Central server defines a site as central data controller
>   
>   * The upsert end point is available to that site (also delete end point)
>   * Query end point is also made (in the same generic fashion as upsert end point
> * if omSupply site is central data controller, UI present central data configuration
>   
>   * Back end queries for records through provided query end point and mutates them with the upsert/delete end point
> * After editing, we do need to sync omSupply site to see new master lists (even though omSupply central data controller site can see 'live' version of central master lists, for operational purposes it would only see updated lists when they synced)
> 
> On back end we use existing layers, repository layer would use API vs Database (but would be made to look and feel like it's a database layer), we swap repository layer when needed.
> 
> I am kind of exiting about this (seems like a good way to transition), but we do have to be mindful how we edit central data, I think for master lists it should be super easy, they are simple.

That has legs. Similarly I think just having a boolean on `site.is_primary` or `.is_admin_site` (to avoid confusion of "central"/"primary") could be used to accept any "central data" update via sync, should forward correctly. Similar idea but using sync system instead of a separate endpoint. There is something to be said for having a separate endpoint that is "online only" though.

**Comment by andreievg** [comment]
>  could be used to accept any "central data" update via sync
> There is something to be said for having a separate endpoint that is "online only" though.

I was leaning toward online only, is there really a use case of needing to configure central data via sync ?

**Comment by andreievg** [comment]
I like the boolean property on site btw, if we go online only that is

**Comment by Chris-Petty** [comment]
> > could be used to accept any "central data" update via sync
> > There is something to be said for having a separate endpoint that is "online only" though.
> 
> I was leaning toward online only, is there really a use case of needing to configure central data via sync ?

That's the premise of sync mirroring, which a few countries do use. As far as I'm aware it's still on the radar for central server to be dumb, and admin to be done via sync. That doesn't necessarily mean we can't have a quick online only version, but it might cause rework down the road if it's not our ultimate goal (not to mention ultimately wanting to do it in central server rewrite).

> I like the boolean property on site btw, if we go online only that is

True, it works for both!

**Qs:** 

Well, I was thinking it through and I think your suggestions here actually answer the questions I came up with 😃.

> * Central server defines a site as central data controller
>    * The upsert end point is available to that site (also delete end point)
>    * Query end point is also made (in the same generic fashion as upsert end point
> * if omSupply site is central data controller, UI present central data configuration
>    * Back end queries for records through provided query end point and mutates them with the upsert/delete end point 
> * After editing, we do need to sync omSupply site to see new master lists (even though omSupply central data controller site can see 'live' version of central master lists, for operational purposes it would only see updated lists when they synced)
> 
> On back end we use existing layers, repository layer would use API vs Database (but would be made to look and feel like it's a database layer), we swap repository layer when needed.

That said, via sync should neatly avoid having to think about most of those questions, going through the usual communication channel. That seems to be a fair bit less complexity; No new separate API to reason about, no thinking about clarifying UI to indicate online vs offline, no juggling the access layers for devs to consider.

Anything that has complexity due to _other sites_ being async still applies, even if you make the changes directly through a REST API on the central server. For instance: 
- Soft deletes of master lists (and various other tables), as another remote site might have used it and have a FK to it (desktop, mobile or omsupply)
- Say eventually managing what stores are on what site across the async system needs orchestration with messages. Whether that's set off by creating the message via sync or online only API doesn't make a big difference.
- Old mirror sync does have some gross complexity in it from editing store-store visibility via primary though, because it makes sure that all the appropriate store records are forwarded between sites (e.g. their item visibility and `list_master_name_joins`) based on incoming `name_store_join` changes (I know this because it's a side thing I fixed on the many journeys of site-rewrite 😢). Either sync v5 would have to add this to it's post syncing tasks, or the REST api would have to handle it (so, the 4D UI has code for it, the v1 API has code for it, and v5 or REST API has code for it...).

**Comment by andreievg** [comment]
Just to re-iterate, API idea is for `transitioning` not for end result. 

> That's the premise of sync mirroring, which a few countries do use. As far as I'm aware it's still on the radar for central server to be dumb, and admin to be done via sync. That doesn't necessarily mean we can't have a quick online only version, but it might cause rework down the road if it's not our ultimate goal (not to mention ultimately wanting to do it in central server rewrite).

Sure, keeping central sync site 'edit free' makes a lot of sense.

> That said, via sync should neatly avoid having to think about most of those questions, going through the usual communication channel. That seems to be a fair bit less complexity; No new separate API to reason about, no thinking about clarifying UI to indicate online vs offline, no juggling the access layers for devs to consider.

Via sync it's very binary, either 4d central configurations or rust central configurations, via 'online' API it's easy to transition.

> Anything that has complexity due to other sites being async still applies, even if you make the changes directly through a REST API on the central server. For instance:

Yep, we definitely should be addressing those when doing central configs with omSupply.

> Soft deletes of master lists (and various other tables), as another remote site might have used it and have a FK to it (desktop, mobile or omsupply)

Yep, wouldn't just be deleting central data tha's FK to site owned remote data

> Say eventually managing what stores are on what site across the async system needs orchestration with messages. Whether that's set off by creating the message via sync or online only API doesn't make a big difference.
> Old mirror sync does have some gross complexity in it from editing store-store visibility via primary though, because it makes sure that all the appropriate store records are forwarded between sites (e.g. their item visibility and list_master_name_joins) based on incoming name_store_join changes (I know this because it's a side thing I fixed on the many journeys of site-rewrite 😢). Either sync v5 would have to add this to it's post syncing tasks, or the REST api would have to handle it (so, the 4D UI has code for it, the v1 API has code for it, and v5 or REST API has code for it...).

Hmm, these two are way beyond the scope of basic central data config, I don't think we implement messages currently for site configurations, and the proposed API would edit things on primary (not on sync mirror site), so existing logic shouldn't be bypassed. 
I was hoping we would avoid mirror discussions for now, I have no idea how things work with that environment, like does it have it's own central change log ?

**Comment by Chris-Petty** [comment]
@andreievg yea fair enough! Agree that stepping stones are good! Keeping it to editing master lists, just thought it might be surprisingly easy to just push it via sync v5 if you want it super fast.

**Comment by andreievg** [comment]
@mark-prins I wonder if we can mark this one as stale and close for now ?

I think this might have come from AV requirements, and I don't remember anyone else is raising this ? Also when we plan out central configuration server transition plan (how and when we bring existing mSupply data configurations to omSupply) we can  add this issue back

**Comment by mark-prins** [comment]
I was AV who were asking. We do need to bring it in, but I agree, not now.
