### ISSUE TITLE
Fridge tag datetime as local datetime

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#2690]
## What went wrong? 😲

When importing fridge tag temperature logs, datetimes are saved in db as is (logs timestamps as utc).

## Expected behaviour 🤔

Would expect datetimes = localtime on the machine that is doing the import,

## How to Reproduce 🔨

Try importing this file: https://github.com/msupply-foundation/temperature-sensor/blob/main/data/FridgeTag%202L/130500109088_202206081014.txt

Find one of the logs in file and compare to UI, it won't match. UTC equivalent will match though

## Solution

Add timestamps offset to upload fridge tag endpoint. 

I've used something like this but just using server local datetime, but the client may not match the server. I am sure that chrono will have a way to convert NaiveDateTime to Datetime<Utc> given a timezone offset.

This is what was done for technet:

https://github.com/msupply-foundation/open-msupply/blob/79a9b5ee08ce8e9b29dfac0d4795255813a1456a/server/service/src/emd_driver.rs#L101-L123

**Comment by adrianwb** [comment]
I'm not entirely sure that this is a bug, as the displayed time in the UI is actually the correct local time. The problem is that the internal time on the sensor itself can't easily be changed once it has been set, as you _really_ don't want to have one hour jumps/repeats in the temperature logs! I think it's reasonable to assume that anyone using one of the sensors would be aware of that?

At the start it matches fine, but as soon as you hit a DST change, the sensor time will be an hour out for half the year until the DST switches back. Even if you convert all the sensor logs to UTC, the displayed time will _still_ be an hour out from the sensor time for half the year, although I suppose at least the temperature logs stored in the DB will match what is displayed in the UI. 

If we are storing all temperature logs as UTC, then we also need to use UTC for calculating breach durations, with particular care around any which happen over a DST switch.

**Comment by andreievg** [comment]
We always store UTC in database, the datetime fields are all in UTC. If I import fridge tag data, in UI it doesn't match the .txt file. Maybe you are not noticing this because you are on UTC time ?

I think DST is a separate question, wouldn't it be a problem regardless ?

**Comment by adamdewey** [comment]
> Would expect datetimes = localtime on the machine that is doing the import,

@andreievg - isn't this different to how we import the data from CCA > Open mSupply?

I thought they were saving as UTC?

**Comment by andreievg** [comment]
@adamdewey, we **have** to save as UTC in database. What we are doing now is taking the datetime from tags (which has no timestamp offset) and just saving in database as if it was UTC time. I am suggesting we should convert datetime from logs to local time of the device doing the import and then save it to UTC.

Example:

Machine that is uploading fridge tag data is in NZT, fridge tag has a log: `2022-06-02 23:06`, currently we will save it in database as `2022-06-02 23:06:00`,  but it should be saved as `2022-06-02 10:06:00` (since NZT is +13 UTC).

> CCA > Open mSupply

It's different, the API for cold chain accepts logs with unix_timestamp, which is then converted to UTC and saved. As far as I know CCA data is correctly saved in Open mSupply, there could be an issue with syncing it to mSupply though, but that's another issue you've raised.

**Comment by adamdewey** [comment]
>Machine that is uploading fridge tag data is in NZT, fridge tag has a log: 2022-06-02 23:06, currently we will save it in database as 2022-06-02 23:06:00, but it should be saved as 2022-06-02 10:06:00 (since NZT is +13 UTC).

Ah sorry, yes I see, that makes sense and definitely sounds like the way to go!

**Comment by adrianwb** [comment]
> We always store UTC in database, the datetime fields are all in UTC. If I import fridge tag data, in UI it doesn't match the .txt file. Maybe you are not noticing this because you are on UTC time ?

That could well be the case - it's definitely more obvious for you in NZ!

> I think DST is a separate question, wouldn't it be a problem regardless ?

Yes, I suspect that'll be a problem regardless of how we store it in the DB. Assuming that the raw temperature log data from the sensor isn't adjusted for DST (I'm pretty sure it doesn't but we'd need to test that to be sure), then I'm thinking that what we need to do is to convert from "USB stick time" (which will be 1 hour off from real local time for half the year) by using the UTC offset of the timestamp when the sensor was activated rather than the UTC offset of the temperature log timestamp?

Once everything is stored in UTC, then that should take care of displaying everything properly in the UI and calculating durations, although it'll still appear to be an hour off for half the year if you compare with the raw sensor data - I don't think there's anything we can do about that as it's a hardware limitation of the sensor itself...

**Comment by andreievg** [comment]
>> I think DST is a separate question, wouldn't it be a problem regardless ?

> Yes, I suspect that'll be a problem regardless of how we store it in the DB

@adrianwb  

I was suggesting that regardless of DST conversion we would have a problem with UTC if we are storing fridge tag records as if they are UTC, instead of converting. I see your comment is mainly focused on DST, the original concern was with UTC vs local date time, just wanted to make sure we are on the same page here ?

I reckon we can post pone DST ? I don't think we need to be fixing/patching an issue with existing fridge tags not knowing DST (for now we can just say that we store date times as they appear in fridge tag, in local time zone), and if our customer will have an issue with that, maybe we can adjust ?
