### ISSUE TITLE
Plural translations not working for Russian language in Dashboard

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#2695]
## What went wrong? 😲

@marthakeezy noticed this, and I can replicate, on dashboard "label.low-stock-items_one" and   "label.low-stock-items_other" are translated but only english version seems to work (and english version changes when translation .json is changed).

Russian translation is shown if not plural though: 

https://github.com/msupply-foundation/open-msupply/compare/main...main(Non-plural-example)

## Expected behaviour 🤔

Plural translation works for Russian language

## How to Reproduce 🔨

In main branch,  go to client folder, `yarn && yarn start`, this runs local front end but connects to demo server. Then you can change language to Russian and you will see that even above strings are translated, Russian version is not shown.

Try change in the above link, you'll see that singular translation is shown

**Comment by mark-prins** [comment]
i18next has support for Russian plurals 😄 

Looking at [the source](https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L19) it has support for three number variants. This [utility](https://jsfiddle.net/6bpxsgd4) allows for checking numbers against which translation key to use. based on that, I had to add `_many` and `_few` to the Russian translation file for it to work. e.g. this version of dashboard.json works as expected:

```
{
  "inventory-management": "Управление Инвентарём",
  "label.expired_one": "Просроченная партия",
  "label.expired_many": "Просроченные партии",
  "label.expiring-soon_one": "Партия, истекающая через месяц",
  "label.expiring-soon_many": "Партии, истекающие через месяц",
  "label.low-stock-items_one": "Товар с запасом менее 3 месяцев",
  "label.low-stock-items_many": "Товары с запасом менее 3 месяцев",
  "label.this-week": "Эта неделя",
  "label.total-items_many": "Итого товаров",
  "label.today": "Сегодня",
  "label.more-than-six-months-stock-items_one": "Товар с запасом более 6 месяцев",
  "label.more-than-six-months-stock-items_few": "Товары с запасом более 6 месяцев",
  "label.more-than-six-months-stock-items_many": "Товары с запасом более 6 месяцев",
  "label.items-no-stock_many": "Товары, которых нет в наличии",
  "heading.shipments": "Поставки",
  "heading.stock-levels": "Уровень запасов",
  "heading.expiring-stock": "Истекающие запасы",
  "label.items-no-stock_one": "Товар, которого нет в наличии",
  "label.have-not-shipped": "Не отправлено",
  "label.inbound-not-delivered": "Входящие поставки не доставлены",
  "error.failed-to-create-requisition": "Не удалось создать реквизицию! {{message}}",
  "label.total-items_one": "Итого товар",
  "label.not-sent": "Не отправлено",
  "label.new": "Новый",
  "button.order-more": "Заказать еще",
  "button.new-outbound-shipment": "Новая Исходящая Доставка"
}
```

though the `_few` translations need to be added - I've only popped one in, and that was because the value my dashboard has is `23` which wasn't working.. and that led me to check, and add in the `_few` key.
