### ISSUE TITLE
Won't let me issue any quantity starting with '1' in outbound shipment in case of stocks are available in multiple pack sizes other than 1

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#2727]
## What went wrong? 😲
 
In outbound shipment, when there are different pack sizes (other than 1) available, weirdly it won't let me issue any quantity starting with `1`, like `101` or `11` or so.

## Expected behaviour 🤔
Regardless of what's available, it should not interfere with what the user wants to input

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Make sure you have stocks available of different pack-sizes, just not 1.
2. Now make a new outbound shipment and add that item
3. When you select that item, make sure you see the below window stating issue [quan] `units in packs of` .
<img width="1016" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/8bd47065-eeda-474f-b9fd-3f2a3f183187">

4. Now try to issue any number starting with 1, like try putting '107' or '12` or so
5. See error: the '1' in your input automatically switches to other number (depending the pack size that's available I think) For me, '107' is changing to '307', '12' is changing to '33'. VERY WEIRD BUG! 

## Screenshots/Recordings
Mobile recordings: [didn't upload desktop recording since it's difficult to show which key I'm pressing in my keyboard in a single screen]

https://github.com/msupply-foundation/open-msupply/assets/59193490/926d17f0-e862-43e2-94df-5172bb5f231f

https://github.com/msupply-foundation/open-msupply/assets/59193490/f9a0880e-d55e-4bd4-8624-cb02f5aa8b6f

## Your environment 🌱

 - Version: v 1.5.03, v1.5.04
 - Platform:
   - [x] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

**Comment by fergie-nz** [comment]
I think what is happening in this case is that when typing anything beginning with 1, the hook will be immediately called which will change the number to a 2 (or the lowest available pack size for issue). Then when you continue typing your number (ie 107), it will come out as 207.

A bit confusing. 

I'm thinking the best way would be to delay the calculation so that typing in a quantity is available to users and it is less abrupt, and also not allowing the OK buttons to be clickable for those 1 or 2 seconds.

I've also noticed that the calculation to adjust up to the lowest available issue-able quantity. Maybe this is intentional, and maybe for another issue.

**Comment by nisha-dangol** [comment]
Tested in v1.7.0-rc1 exe

### Tests
- [x] Have some stock for an item, which has pack sizes other than 1
- [x] Create an outbound shipment, add that item
- [x] Issue a quantity for a number which contains multiple digits and starts with 1 e.g. 10 or 105 etc.

Also, the original issue is not replicable as well, so PASS!
