### ISSUE TITLE
Update to Diesel 2.0

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#2881]
## Is your feature request related to a problem? Please describe 👀
As per title. Current diesel version is `1.4.7` but we want the latest version which is `2.1.4`. This will require dependancy crates to be updated as well: 
- diesel_derive-enum: `1.1.1` -> `2.1.0`
- diesel_migrations: `1.4.0` -> `2.1.0`

**These are all major updates, so lots to change and many files will be touched**

Changelog for diesel can be found [here](https://diesel.rs/changelog.html). Current progress so far has just been renaming/changing macros, etc. 

### Additional context 💌
Progress can be found in [this branch](https://github.com/msupply-foundation/open-msupply/tree/update-diesel).

**Comment by andreievg** [comment]
One big thing is connection would now be mut. And we do want to make all of the repos async and use worker thread as per: https://github.com/msupply-foundation/open-msupply/issues/78.

Btw this work would need to be coordinated between teams, since it's a major change that will likely cause conflicts, I think it should be done once all of the feature branches are merged, and should be merged pretty quickly to develop (and all of the PR branches updated)

**Comment by clemens-msupply** [comment]
I wonder if we can use diesel 2 and diesel 1 in parallel. Think for this we would have to reuse the database connections /manager (otherwise I would expect problems for sqlite).

But I think we can wrap an existing connection into a diesel 2 connection.

If this works (easily) we could slowly migrate to diesel 2 starting with a simple repository.

**Comment by andreievg** [comment]
> EDIT: macros seem to refer to diesel:: so I don't think its possible.

What if all of the diesel 2 repos are in another crate ?

Me and @jmbrunskill were also wondering about doing it in parallel, and had questions about sqlite connection/pool/transactions

**Comment by clemens-msupply** [comment]
I continued with @roxy-dao `update-diesel` branch for a little bit and made some reasonable progress in the repository crate. However, I hope it will not cause too much pain in the upper layers (mut connection + async might be trouble / will require a Mutex...)

Another problems I saw is that most repos are also JOINing other tables, and I somewhat discarded the idea to do it gradually/ in multiple crates...

@andreievg I will ask you for help with `repository/src/db_diesel/temperature_chart/temperature_chart_row.rs` though there has been some bigger breaking changes :(

**Comment by andreievg** [comment]
Oki, are we going to be using this pattern: https://github.com/msupply-foundation/open-msupply/issues/78 ? It's a bit of work to refactor, but I think it would make things pretty future safe

**Comment by clemens-msupply** [comment]
Yes! However, in the first step I am trying to keep the change minimal and close to the existing implementation. Let see how far I get (I am currently adding lots of lots of `mut` keywords and I fear I have to remove them again...)

**Comment by andreievg** [comment]
Ahh ok, i was thinking that with that pattern you won't need to add mut, but would need to use callback ¯\_(ツ)_/¯

**Comment by roxy-dao** [comment]
Removing from tester board since change isn't obvious
