### ISSUE TITLE
Currency input incorrect for price

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#2918]
## What went wrong? 😲
Typed in 50 for the price... but it gets converted to 5.00 when out of focus

https://github.com/msupply-foundation/open-msupply/assets/61820074/412d3193-0841-48c9-963b-920052aedd1d

Also typing 100.00 converts to 1.00

https://github.com/msupply-foundation/open-msupply/assets/61820074/2e118cb8-3de4-40ce-b17e-92791ff18719

## Expected behaviour 🤔
Should display/save the correct number

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to an 'Inbound Shipment invoice'
2. Click on 'New line'
3. Add any item
4. Go to price tab
5. Enter a 2 digit or more number without decimals

## Your environment 🌱

 - Version: 
 - Platform:
   - browser (extra points if you tell us which one)

**Comment by CarlosNZ** [comment]
Can confirm that this problem is with the Currency Input component, as you can see the bug in Storybook as well.

Having a quick look, I see we're using an external package [react-currency-input-field](https://www.npmjs.com/package/react-currency-input-field) in this component -- just wondering if this is still needed? I think with the new standard "NumberInput" (#2794), we can handle the formatting ourselves (using `Intl.NumberFormat()`)? I'm happy to follow up on that when #2794 is merged if you like?

**Comment by CarlosNZ** [comment]
This has also been listed here: https://github.com/msupply-foundation/open-msupply/issues/2932

My suggestion is what I wrote on that issue:

>  See if "react-currency-input-field" can be removed and just use the built-in IntlNumber.format() function to do what we want

I think if we just consolidate the currency input into the existing NumericText input (with additional formatting options), this problem will go away.

However, I won't do it in the Number input fixes, as that's more urgent and this will take a little more time, so I'll leave this issue here to fix that.
