### ISSUE TITLE
(Possibly) Invalid mapping of mSupply transact.tax to OMS invoice.tax

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#3018]
## What went wrong? 😲

https://github.com/msupply-foundation/open-msupply/blob/7e4320318f0ff74d9b9fb340515ae33099863d6c/server/service/src/sync/translations/invoice.rs#L245

I'm finding it hard to track in our code base whether `tax` is consistently the tax percentage to apply to line (and what factor representation it is in, is 10% -> 10.0, 0.1 or 1.1) or actually the tax component of the line (i.e. $30*10% = $3.0). I'm pretty sure it's generally not the last in OMS, but legacy mSupply it is the last... sync translator is treating it as the factor. I've seen some places explicitly call variables for tax `tax_percentage` which is much clearer.

If we wanted to be super rusty maybe we could make a type aliases for `type Tax = f64` (or TaxTotal) and `type TaxPercentage = f64`, along with rustdocs explaining precisely how each is meant to be used. (@clemens-msupply perhaps another reason to have domain object types separate from the diesel record types 😃, or maybe diesel wouldn't mind a straight alias of f64... )

## Expected behaviour 🤔

Tax calculations and values should always be unambiguous in the codebase. Sync translation needs investigation for inconsistency. If inconsistent, we must decide either mapping the values from legacy records with a calculation or reimplementing tax in OMS (surely the former right?).

## Solution

https://github.com/msupply-foundation/msupply/issues/10118#issuecomment-1966107074
>@Chris-Petty Oh. OMS was supposed to fix all the badness in mSupply, it wasn't supposed to leak over! Changing the field name on Open mSupply would be a REALLY good idea.

😁 

- [ ] we should rename `invoice.tax` to `invoice.tax_rate` to reduce misinterpretation.
- [ ] if not keeping `invoice.tax` (tax_amount), it needs to be translated when pushing to legacy. (Or we keep it and populate it too for a straight translation)
- [ ] Add transact.tax_rate to mSupply (migrate past data to populate, all UI invoice logic to update it correctly)
- [ ] In incoming translator save tax_rate from tax_rate if mSupply provided it. If not, calculate from `tax`. Either that or we increment the API compatibility of OMS to require a later version of Legacy Server?

## Additional context

mSupply doesn't have an `invoice_line.tax`, tax was applied at the invoice level across the total price of all lines. omSupply moved taxes to the the `invoice_line.tax` as that allows different tax rates for different products (for NZers think GST exemption being considered by govt for fresh produce, or products like cigarettes and alcohol having specific additional taxes applied with GST on top of that (IDK if it's already handled before retailers, but anyway).

## How to Reproduce 🔨

Steps to reproduce the behaviour: (UNVALIDATED as of writing)

1. Have a legacy desktop store's customer invoice with a given tax value
2. Sync the store/site to OMS
3. Check the tax hasn't essentially gone wacko

## Your environment 🌱

- Version: Probably all for the last couple years, but I'm looking at 1.7.0 `develop` code.
- mSupply version: Been the way it is for eons, but 7.13 right now.

**Comment by Chris-Petty** [comment]
Ha a relevant mSupply issue. This is why recording the actual tax rate is important... https://github.com/msupply-foundation/msupply/issues/10118

**Comment by Chris-Petty** [comment]
Pretty sure the issue is valid, doesn't need discussion. Someone will find out if I'm wrong though.

High priority as I'm not sure if transfers transfer any tax information, in which case this is a production bug that could be occurring anywhere that bothers entering tax. Though... transfers don't typically move money.

**Comment by Chris-Petty** [comment]
@andreievg 
> In incoming translator save tax_rate from tax_rate if mSupply provided it. If not, calculate from tax. Either that or we increment the API compatibility of OMS to require a later version of Legacy Server?

In the solution, this last point what do you think? Have some Optional fields in the legacy struct because we dunno what version of legacy we're talking to (or have different structs for different legacy versions lol), or increment and say "OMS requires a central server version of at least X (where we added transact.tax_rate)? I'm thinking the latter.

**Comment by nisha-dangol** [comment]
Since I'm not really satisfied with the test-suites in #3691 , I did these:
- Created some outbounds/CI with tax-values, service-charges & other-charges from OG-desktop-store
- Migrated that OG-store to oms-store
- Rechecked those outbounds

Hi @roxy-dao Could you confirm these?
Issues found:
1. The tax-value from mSupply is not mapped correctly to oms
<img width="1076" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/eb9f75a3-d82c-49ad-9b1c-b691d6e04dec">

<img width="1488" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/6aa99043-8cc2-4a2d-a252-9c4ab35d7ee2">

<br><br>
2. The `other-charges` from mSupply is also not mapped properly in oms (I believe there is no UI for this in oms yet)
<img width="1081" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/738aa58f-0e37-44fa-b10a-a11d824004b2">

<img width="1501" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/a9fc8e47-5449-402c-9a0c-7237dc41b15b">

<br><br>
3. The `service-item-charges` value from mSupply don't reflect properly in oms. I think there's issue already submitted for this: #3554
<img width="1084" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/ecb1f59a-ff7b-4fd6-a3f8-9678b0f792bd">

<img width="1496" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/15cde2e4-f0ef-471f-81f3-e7f43a356a0c">

<br><br>
4. On migration to oms, the sub-total value from mSupply is showing incorrectly as `Foreign Currency Total` instead of `Grand total`?
<img width="1076" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/34b75ad1-d1ee-4b25-ba99-c5fdddf474a0">

<img width="1488" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/05ef7370-d368-4f9d-8e59-216d249db010">

**Comment by roxy-dao** [comment]
> Hi @roxy-dao Could you confirm these? [I've also uploaded the datafiles [here for reference](https://drive.google.com/drive/folders/1VWd91YKiUtMxRPBh5UxT9VhHzIW_2bNA)]. Issues found:
> 
> 1. The tax-value from mSupply is not mapped correctly to oms
> 
> 2. The `other-charges` from mSupply is also not mapped properly in oms (I believe there is no UI for this in oms yet) 
> 
> 3. The `service-item-charges` value from mSupply don't reflect properly in oms. I think there's issue already submitted for this: #3554 
> 
> 4. On migration to oms, the sub-total value from mSupply is showing incorrectly as `Foreign Currency Total` instead of `Grand total`? 

1. Yeah looks like it's not. This is because mSupply and OMS does things differently for price. Will need to create another issue to encompass all invoice/invoice line price mapping so that migration can happen. This will also solve 4.
2. We don't do `other-charges` in OMS, also different from tax issue.
3. There's already an issue for this yup

**Comment by nisha-dangol** [comment]
> 1. Yeah looks like it's not. This is because mSupply and OMS does things differently for price. Will need to create another issue to encompass all invoice/invoice line price mapping so that migration can happen. This will also solve 4.
>
Submitted issue for 1 & 4: #3965 

> 2. We don't do `other-charges` in OMS, also different from tax issue.
> 
okay; will discard this then
