### ISSUE TITLE
Cold Chain: sensors are duplicated after uninstalling and re-installing the app

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3153]
## What went wrong? 😲
 

A few weeks ago, I had to reinstall the omSupply & CAA applications to test the issue of upgrading to different versions. After re-installing, and setting up the applications again, I noticed that the sensors are duplicated - you can see a set of them stopped working on 19/01, and another set is collecting data to this day.

Other issues:
- If you uninstall the app with an ongoing breach, and then re-install it again, the breach notification is still there but there is no way to remove it/acknowledge the breach. You cannot acknowledge the breach for the original sensor, if it's been duplicated. 
- There is no functionality to remove/delete the sensors to tackle the above, or in general. 

My train of thought is: if sensor 1 was breaching a month ago, and then it's breaching again now, the first breach should be automatically removed/acknowledged? Because one sensor can only be a part of one breach at any single time?

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/f17a499b-8524-4ff8-b4b9-fa9c5216c3da)

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/2d9dd979-c7f8-449a-a474-0c6ec0038c66)

## Expected behaviour 🤔

1. If the apps are uninstalled, the sensor IDs should match-up behind the scenes and not duplicate. 
2. Also, you should be able to acknowledge the breaches even if the app was uninstalled and re-installed, or even if a specific sensor is not in use anymore. 
3. In addition, I think it would be good to have functionality to remove sensors, or at least deactivate them?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Connect a few sensors to CCA, and then CCA to omSupply to receive the temperature readings
4. Make sure to produce an ongoing breach, but do not acknowledge it
5. Uninstall both apps, install both apps again, set up your environment
6. Connect the same sensors
7. Now check under Cold Chain -> Sensors -> notice duplicate sensors
8. Notice the breach notification bar -> try to acknowledge the breach of the sensor that was before re-installation
9.  Click on any sensor - you are not able to remove it from the system

## Your environment 🌱

- Version: omSupply: 1.6.02
- CAA version 0.5.6

**Comment by Chris-Petty** [comment]
Good testing thanks!

@marthakeezy Just to clarify steps 4 onwards. When you connect the same sensors to the app, I assume CCA creates 
new UUIDs for them rather than some maybe unique ID from the sensor itself (if that's even accessible in the sensor API). 

Can you confirm that you get duplicates from this cut down version of steps?

1. Connect a few sensors to CCA, CCA connected to omSupply and syncing
2. get a breach don't acknowledge
3. Uninstall just CCA, Reinstall
4. Setup the sensors again
5. OMS has duplicate sensors

Tipped off just now that @jmbrunskill apparently [changed the sensor IDs sent to be derived from the MAC addresses](https://github.com/msupply-foundation/msupply-cold-chain/pull/274) of the sensors (so should be unique and consistent between installs of CCA). So I thiiiiink this part should be in CCA repo.

For the other bits:
- Unable to acknowledge seems OMS bug.
- Can't delete sensors, trying to keep record of what device recorded what logs. Would want to clean up the sensor list though, should have a disable/soft delete I'll write a feature request.

**Comment by marthakeezy** [comment]
Hey @Chris-Petty!

I just uninstalled CCA, installed it again, re-synched with omSupply, reconnected the sensors and the duplicates are still appearing in the app. I am still unable to acknowledge old breaches. Let me know if anything else can be tested? 

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/55d3e043-4cbc-455c-808f-4fac27896abe)

**Comment by Chris-Petty** [comment]
Ah so it didn't make more duplicates? Weeeeird.

**Comment by jmbrunskill** [comment]
Maybe her original install was an older version. If the ID are already in the old format, they don't get re-created. So we'll still have this re-initialise issue for older installs of the app.

**Comment by jmbrunskill** [comment]
This is expected behaviour if sensors were originally created with the old version. After re-creating them once they'll then be consistent after reinstalls...
