### ISSUE TITLE
Two different lines of same name in suppliers list after merge on cloud

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3276]
## What went wrong? 😲
 
Two different lines of same name in suppliers list after merge on cloud.
Since it looks bad (having two suppliers of same names in a list); I'm calling this High severity!

## Expected behaviour 🤔
After merge, merged names should show up as one

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have two different names visible to your oms-store first
2. Merge them on desktop cloud
3. Sync
4. See the suppliers list
5. See error: two different lines of same name. 
<img width="1036" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/6ede8b6d-51a2-409f-a149-e8ebcd541a5b">
Note that in other transactions, merge looks good though; the merge-effect can be seen in transaction names! Maybe a simple UI bug? 

## Your environment 🌱

- Version: v1.7-rc2 exe
- mSupply version: v713-beta22

- Platform: 

- Database type: sqlite

**Comment by Chris-Petty** [comment]
Phew an easy one, and not too dire. I believe it's just because we forgot to clean up effectively duplicate name_store_joins after the merge.

![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/82e22d33-1239-4770-b66b-276758cb4a31)

So the name_store_joins have different name links, but the links are merged going to the same supplier. I assume our queries don't filter distinct when returning suppliers that are visible.

I'll just delete the NSJ, though it does mean if we ever "undelete" visibility won't return. That's probably OK, I think undeleting will be a rarity and when done this is a small price to pay.
