### ISSUE TITLE
All available servers are showing on the Discovery page when connecting to omSupply

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3377]
## What went wrong? 😲
 

When upgrading to v1.7.0-RC3 yesterday with Chris, we have discovered a few issues:

1. Maria's IP address is not visible in the list of possible servers to connect to
2. There are too many options displayed on the page - Chris mentioned it's showing all available servers? For example, I was connected to Haiti's Demo Server
3. There should be a functionality to perhaps enter your IP address if it's not showing?

<img width="1189" alt="Screenshot 2024-03-21 at 5 09 38 PM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/6d11f357-1e65-4a64-af6d-f27ca2600a98">

## Expected behaviour 🤔

1. Maria's IP address should be visible
2. Less servers/only the necessary ones should be displayed
3. There should be a functionality to enter your IP address if it's not showing

## How to Reproduce 🔨

Steps to reproduce the behaviour:

I am not entirely sure the issue is reproducible - happy to offer my laptop for testing if needed? But I did a fresh omSupply installation with Chris and the issue was there, with the IP address not visible. 

## Your environment 🌱

- Version: initially, v1.7.0-rc2, then v1.6.3, then 1.7.0-rc3
- mSupply version: version: v7-13-00-Beta25

- Platform: Windows Server 2022 Desktop

- Database type: ?

**Comment by mark-prins** [comment]
The root problem is that there are a lot of servers on the same network! If this is a virtual hosting environment, then the network configuration would need to be updated so that you cannot see other servers.

> only the necessary ones should be displayed

I don't see how we could determine what is necessary or not. This example is a special case, where there are a lot of servers running!

I had thought of adding the option to enter an IP address, but didn't because I thought that if the server is running, it should be showing! allowing manual entry is a way of letting people connect to invalid servers / addresses i.e. it enables people to make mistakes. Will reconsider that opinion as part of #3323

**Comment by Chris-Petty** [comment]
@mark-prins as I understand it Desktop broadcasts on UDP and the servers respond saying where they are - can Desktop get the local machine IP and if any of the responses match put them at the top of the list?

Agree that it's valid to show all the available servers (even if sorta unusual), can't really reduce them. But do we have a limit on how many are shown?

**Comment by mark-prins** [comment]
there's no limit - and I don't think there should be. This is a very unusual setup, and if we limit servers displayed it would cause issues rather than help.

Put local server at the top though? 

( can we sort the list based on physical proximity 🤔 )

**Comment by DhanyaHerath** [comment]
The solution to this can be done through https://github.com/msupply-foundation/open-msupply/issues/3323, closing this one in favour of that change
