### ISSUE TITLE
Re-design the Admin -> Synchronisation area

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3407]
## Is your feature request related to a problem? Please describe 👀

As a part of 1.7.00 release testing, I noticed that under Admin -> Synchronisation, password is required to change the interval in seconds. Without entering the password, it is impossible to save the changes - which should not be the case. 

After speaking to Andrei, this is the latest explanation: 

`Technically password is not needed, Sync should be in two parts, one to change interval (and number of sync records), the other part to update site info (url, site name and password). This can possibly be done as part of number of sync records, which is likely needed to improve client A's sync`

https://github.com/msupply-foundation/open-msupply/assets/153777484/71d5f93b-a33a-491b-b14c-9c558732ea1a
 
## Describe the solution you'd like 🎁

As per Andrei's explanation above, the Synchronisation area should be split in two, allowing some records to be updated without having to enter the password. 

### Describe alternatives you've considered 💭

N/A

### Additional context 💌

N/A

### Moneyworks Jobcode 🧰

N/A

**Comment by marthakeezy** [comment]
@andreievg ^

**Comment by Chris-Petty** [comment]
@marthakeezy to clarify, do you need to enter _the_ site password, or can you put in any password (updating the password and the interval at the same time)?

**Comment by marthakeezy** [comment]
@Chris-Petty you need to enter the old password, as if you enter another one, you get this error message :)

Actually, just made me realise there is no functionality in omSupply yet to change the pw

<img width="557" alt="Screenshot 2024-03-26 at 2 13 07 PM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/9dcd1903-0694-4b48-9ccc-ea4ab345b392">

**Comment by Chris-Petty** [comment]
Right thanks. Yea I don't think it's clear the intent is to use the password for permission to save.

Being able to update the password is probably pretty low priority. Maybe some niche circumstance. In the past it's been used as a kludge to stop sync but it's not great (and I'd prefer to do it on the central server). 

Generally you never want to change the site/password - if you need to change the site you must reinitialise OMS with that site. If someone absolutely INSISTS that either need to be changed on the central server (because typos are unbearable) and the remote needs to match then you'd need to be able to update. Easier to just say "no" though 😁 .

**Comment by marthakeezy** [comment]
Gotcha, thank you for the clarification!

**Comment by jmbrunskill** [comment]
@andreievg feels like this would be a good refactor week candidate?

**Comment by andreievg** [comment]
Refinement, we considered use case very unlikely with very small impact, closing.
