### ISSUE TITLE
Able to login on browser despite the site being attached to a hardware ID (desktop app)

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3517]
## What went wrong? 😲

During a few tests with @roxy-dao we were able to login on browser despite the site being attached to a hardware ID (desktop app)
![Screenshot 2024-04-03 at 1 56 07 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/45e49a86-f83e-42c2-9826-d4271e08b834)
![Screenshot 2024-04-03 at 1 57 01 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/28ed01b0-27e0-4dc4-8fd9-e1a6dd299559)

## Expected behaviour 🤔

If a site is attached ot a hardware ID you cannot login into browser

## How to Reproduce 🔨

Choose a site that is attached to a hardware Id. 
Login to browser using credentials for a user that has access to this site.

## Your environment 🌱

- Open mSupply Version: 1.7.RC3
- Legacy mSupply Central Server Version: V7.13

- Platform: browser (chrome)

**Comment by roxy-dao** [comment]
Update: You can't sync, but can still view all data that was synced beforehand

**Comment by clemens-msupply** [comment]
Could you provide more details about your exact setup? 

Do you have an omSupply remote site and log into this server using chrome? And then you change the hardware id on the central server? This means sync fails, but remote site is still running.

I would say this is expected behaviour. However, question is if we should kill/stop the remote server if this hardware id mismatch is detected? However, the damage might already be done, e.g. if changes have been made on the remote site, these changes will be lost if a different remote server is taking over permanently.

**Comment by regotaina** [comment]
> Could you provide more details about your exact setup?
> 
> Do you have an omSupply remote site and log into this server using chrome? And then you change the hardware id on the central server? This means sync fails, but remote site is still running.
> 
> I would say this is expected behaviour. However, question is if we should kill/stop the remote server if this hardware id mismatch is detected? However, the damage might already be done, e.g. if changes have been made on the remote site, these changes will be lost if a different remote server is taking over permanently.

Basically I connected to desktop app first. Then logged on the browser. 
I didn't change the hardware ID at all, the server kept the 1st one from desktop app.

I was able to see transactions and even create an inbound shipment. However I could not sync, creating the situation you described, of transactions being lost.

**Comment by clemens-msupply** [comment]
You mean you used omSupply desktop connected to a local remote server (standalone installer)? What is the url you connect to in the browser? to the one for the local remote server?

Its sounds like you have two remote server running somewhere?

**Comment by Chris-Petty** [comment]
@regotaina I think we still need more reproduction steps, as we're still not 100% sure what you mean:

> During a few tests with @roxy-dao we were able to login on browser despite the site being attached to a hardware ID 

User login in the OMS app to a remote server (via browser or app) is a completely separate authorisation to the remote server sync authentication to the central server, the latter being what the hardware ID matters in. 

If you're sure you didn't change the hardware ID on the central server, then perhaps an explanation is that somehow in your steps OMS changed what it thought its hardware ID was, I don't think there is any mechanism for this though. 

I'm aware a month or so ago that many people were having confusion when using the desktop app on cloud servers as it was very easy to be connected to the wrong "remote" server on cloud VPS. Is it possible your browser was connected to "taina.msupply.org" but your desktop app was connected to a different remote server on CloudVPS that was working correctly?

If it's been too long since you had the issue and you don't have it anymore, it might be easier to close this issue until you see the problem again.

**Comment by mark-prins** [comment]
echoing Chris's comments - can we close the issue?
I'm still not clear on the scenario - but generally, having multiple clients login to a server is acceptable.

**Comment by regotaina** [comment]
Ok, @Chris-Petty clarified! @roxy-dao and I thought that once you're logged on Desktop app, if you attempt to login on browser, it should lock you out.

However, the expected behaviour in this case is that the browser acts like a client, therefore, there's no problem on being logged on 2 devices at the same time. The hardware ID should not stop users to login on browser.

The good thing is that we picked up another minor bug with sync and timezones... but that's another story for another issue. Thanks team! 👍🏾 

Closing this issue now.
