### ISSUE TITLE
Simplify Cold Chain Graphing

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3679]
## The suggestion

Currently the cold chain graphs have been a significant source of bugs and confusion in open-mSupply.

I argue that a simpler graph view would serve the needs of the users better and reduce the confusion and complexity but would have some limitations.

I propose that chart should show every datapoint in the selected time range and use a dotted line to connect them.

Something similar to this...
https://master--63da8268a0da9970db6992aa.chromatic.com/?path=/docs/api-cartesian-line--docs

<img width="1025" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/8287373/129b68d0-6298-4259-a1b2-c2107b6acb60">

This is easy to understand, as you see all the datapoints from the system and the dotted line shows clearly that the gaps between the datapoints are interpolated not `real` data. The user can visually see if datapoints are further apart than previous ones indicating a gap, and can evaluate the severity of it.

To avoid the browser crashing with too much data, we'd need to limit the time range that the user can select.
This would mean if the user has a use case where they need to look at a long time range, they'd need to go to the dashboard to investigate (BTW: We know the dashboard can crash the browser by using too much memory when trying to draw too many datapoints on grafana too)

### Why should we invest time in this?

We've already sunk a lot of time in to the queries and graphs for cold chain data, yet bugs and confusion still abound.
See this for the latest: https://github.com/msupply-foundation/open-msupply/issues/3283

The current graphing approach isn't easy to understand for users, and developers need to keep checking data and logs to understand differences between the datapoints, the query logic, and the graphing view.

Alternative approaches with options to customise when something counts as a `gap` allowing the user to select different kinds of aggregations, etc all would result in a lot more work for us.

### Are there any risks associated with this change?

I think it reduces risks of mistakes and future bugs, but does potentially introduce new bugs with the updated code.

### How much effort is required?

This feels like around 1 day's work to me, but how we limit the time range might be a little bit complex?
We'll need to evaluate the risks of trying to display too much data, particularly on a tablet, but I think in general people understand if something is slow when trying to look at a lot of data...

**Comment by jmbrunskill** [comment]
Aim to be able to display data for 30days for 1 sensor at a 5 minute interval 30*24*(60/5) = 8,640 datapoints?
A 30 day range it useful as a trouble shooting tool, finding when a sensor stopped working, or just giving the user confidence that the data collection seems reliable for the last 30days...

Need to test what happens on tablet if they do have more sensors, eg. If we have 5 sensors @ 1 minute (216,000) data points does the whole app crash, or just take a long time to load? That's probably a reasonable upper limit...

**Comment by fergie-nz** [comment]
Nice James, I like it

I personally would even go further and argue that a line connecting data points implies that there has been a smooth change between temperatures. This isn't always the case, particularly when there is a large gap between data points. For example, within a couple of hours the fridge could be left open for an hour, heat up, get closed again, then cool down.
If the graph reading literacy of our users is not high, I think even a dotted line could be miss-leading, and so I still wonder if no graph at all is better. 

I'd love to have more insights under the hood with some simple maths to say that given a given uncertainty (which could be caused by big gaps in data measurement OR high variation within the measurements), a data range is flagged to alert users. Otherwise I imagine it is too easy for a user to see that the line is within bounds and assume everything is fine.

I imagine some other things to consider and maybe needs consultation or in the field experience.
Though here are some things I can think of:
- Fridges being opened / switched off / medicines being outside causing short term spikes which could be missed
- On/off cycles of a fridge causing a high COV, yet is still safely within bounds at all times
- More uncertainty in the system from measurement, difference in temp between medicine and thermometer, temperature gradients within a fridge (though I'm sure this has all been considered in safety margins already)

**Comment by mark-prins** [comment]
Thanks James - I'm on board for this. It would mean removing the chart data diesel query and adding a limit to the graphql endpoint for the chart. I would throw an error if too many datapoints are in the range, and display the error on the f/e.

Removing the chart is the best option for avoiding the ongoing chart issues, but I am reluctant to do this. I still think there's value in being able to visualise the data. As long as it's accurate.

Am not too keen on the dotted line, as I agree with Ferg, that any connecting link implies a contiguous dataset. Open to giving it a try. What would be cute is to have the opacity of the line relate to the number of nearby datapoints, I wonder if that's possible.

@adamdewey - you're the champion for the chart, how do you feel about these changes? We still have a some open chart related bugs ( #3090 and #3283 ) and have spent a lot of time on the chart to date. This option would, I think, resolve the outstanding issues and provide more certainty in the chart data.

**Comment by adamdewey** [comment]
Hey @mark-prins and @jmbrunskill 

I like the idea of plotting all actual datapoints on the graph - it would make it useful as an actual analytic tool rather than more of a vague representation. 

But am wary that we might hit technical limitations, especially on tablets with low hardware specs. 

I'd be curious to know how it behaves for the 8640 datapoints that James mentions. 
There might be facilities that are using multiple sensors on a tablet, so we'd need to be able to give them a way to be able to see 30 days of data for a 5 min interval sensor (it's ok if we can only show 1 sensor at a time)
Not too worried if it takes a little while to load the data, but would be bad if the experience is laggy once it has loaded and/or crashes the app. 

Appearance-wise:
- I agree with Mark and Ferg, we shouldn't show any line for periods where we are missing data. 
- I think the current solid line is good, don't think the user will misunderstand once they can see the datapoints
- Unsure on showing the datapoint number values - I think it might get a bit busy with multiple sensors on a graph? I think just having a dot would be enough to make things clearer to the user?

**Comment by adamdewey** [comment]
Instead of showing the datapoint numbers, could we show them on a touch/click of a dot, perhaps?

**Comment by jmbrunskill** [comment]
> Instead of showing the datapoint numbers, could we show them on a touch/click of a dot, perhaps?

I agree just a dot is fine, I just didn't want to do a whole extra mock up!

**Comment by Chris-Petty** [comment]
Nice!

Ah just realised there is some interactivity right? But if there wasn't then for the CCEI charts I was wondering if it'd actually be more performant to generate SVGs on the backend and send them to the frontend? Maybe not SVGs with 8.5k data points thought haha. 

Could have a chart that shows for last 30 days what days had breaches, then click on a day which shows which hours had a breach, then click again to see the readings plotted for the hour?

Afraid to repeat something from being out of the loop - but I guess the ultimate goal of the plots is to see when exactly a breach happened as a lead on what exactly may have caused the breach? Are there other use cases other than looking awesome 😁?

**Comment by adamdewey** [comment]
It's a fair ask to request user stories - we never actually spec'd any originally. 

Having the visual graph serves many user stories and I probably couldn't think of them all explicitly off the top of my head, but some that come to mind just now: 

1. To spot when a breach occurred
2. To understand how long the breach went on for and for how long it was over the threshold
3. To see how many breaches have occurred recently - is there a pattern?
4. To get a visual for generally how close the average temperature is to either of the thresholds
5. To spot any gaps in data - when / how long have we been 'in the dark' ?
6. To spot patterns between multiple sensors - are they doing the same thing? Is one erratic?
7. To be reassured that things have been / and continue to be monitored
8. To visualise the fluctuations in temperature - big swings or small? Is the CCE on last legs or performing well?

**Comment by marthakeezy** [comment]
Tested Cold Chain graphs as a part of [this issue](https://github.com/orgs/msupply-foundation/projects/32/views/8?pane=issue&itemId=54683509), all working as expected with the exception of one inconsistency which was logged as a bug. Build test passed! :) ✅
