### ISSUE TITLE
Feature flag for pack variant UI

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3684]
## Is your feature request related to a problem? Please describe 👀
The pack variant UI has now been shown to PMs and concerns have been raised at the scope of the changes and the lack of general input.

We would like to have some time to consider how to proceed - to that end, please can we keep the functionality of pack variants, while restricting UI changes to a feature flag .

## Describe the solution you'd like 🎁
Implement a feature flag for the pack variant work. This will
* Revert the column changes ( changing unit and pack size to a single column called `Pack` )
* Remove the pack variant selector component

enabling the feature flag will re-enable these items.
All the api / backend work can remain without causing any impact.

The configuration of pack variants in the central server can remain too, the impact of that is low and won't cause an issue for most users.

### Describe alternatives you've considered 💭
I don't see that we have time to rollback all the pack variant work, nor do we have time to have PMs agree on how to proceed, or give Anisha enough time to review. Not without delaying the release of 2.0.00 significantly.

**Comment by andreievg** [comment]
@lache-melvin

There is also an issue i was talking about, with performance. In order to figure out what's the default pack variant, we do some statistical analysis of used batches for item, and i think we do it for all of the items, not just pack variant ones. 
If we hiding the feature i think we can comment our or skip that bit of code for now. I thing the long term fix would be to create an sql statement for this logic (vs doing in rust), I think this is also worth mentioning in the comment:

https://github.com/msupply-foundation/open-msupply/blob/dc5e2da83082eee01fd452e4ce7ba320d1a3a493/server/service/src/pack_variant/query.rs#L12-L13

I was wondering if you can comment out that extra logic from this method (as part of this issue), I think it would be fastest way to eliminate my concern for now (otherwise we would have to validate that it is indeed performance issue, and spend a bit of time assessing if it's worth doing now etc..)

**Comment by lache-melvin** [comment]
Closed by #3719
