### ISSUE TITLE
Adding reasons to inbound or outbound Returns does not sync unless you open a new window

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#3696]
## What went wrong? 😲
Adding a reason on legacy msupply for returns and clicking sync does not transfer the reason on to OMS. Need to open a new browser window for the reason to appear.

## Expected behaviour 🤔
Sync should make the reason appear without needing to open new window?

## How to Reproduce 🔨
Legacy > Add reason for returns
OMS > Sync
Inbound or Outbound Returns > select item > add reason (look for added reason)

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: 2, desktop browser
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by CarlosNZ** [comment]
Interesting, it's probably due to using cached queries. And if so, it probably affects more than just this. I guess we could just invalidate the whole Tanstack cache after a manual sync?

**Comment by mark-prins** [comment]
we'd want it to work for automatic sync as well - adding to manual sync only would likely only solve the testing situation. Though.. for normal operation, this issue is very unlikely to come up, and we may only need to address the manual sync / testing scenario.

I wouldn't want to invalidate the entire cache on every sync, that seems extreme. Better to be targeted and look at the cache settings for the reasons query - worth checking how long the reasons are retained in cache.

**Comment by lache-melvin** [comment]
We cache the reasons query for 5 minutes - same for inventory adjustment reasons. Have we ever had any issues with them? Log out/in again also invalidates (though new window might be faster 😅)

**Comment by mark-prins** [comment]
I think it's not really an issue then - can we close?

**Comment by lache-melvin** [comment]
I think so, thanks Mark 🙏

**Comment by lache-melvin** [comment]
This was raised again by @AnushaUp [here](https://github.com/msupply-foundation/open-msupply/issues/3567#issuecomment-2149714938), for stocktakes rather than returns...

What I realised in that video is a use case (pretty low likelihood, but possible):

- Inventory adjustment reasons are added to central OG
- They are synced to OMS
- OMS UI still has cached reasons query (i.e. thinks there are no active reasons, so reason dropdown is disabled)
- OMS backend DOES know that reasons are configured, and requires them, so you get an error trying to save the stocktake line

Given this has been raised twice, and the above use case, I'm kind of wondering how valuable it is to cache the reasons at all? It's a really small query, not much data, and seems to be causing more confusion than help, at least from a testing side...

Reopening to be re-triaged 🤷‍♀️ 

Also, logout/in again doesn't invalidate cache like I thought, but refreshing the page does 👍

**Comment by andreievg** [comment]
Triage, reasons would typically be configured at the start, before any sites are deployed.
Another use case is new reason added, not appearing. There is a work around of restarting app or refreshing the page. 

Also suggest we have a discussion to think about what we are targeting in terms of caching (do we want a cloud app that works in low connectivity, or are we ok with existing sync system and local servers having good connection to that front end).

As per above probability of it happening is still considered low, impact is highish but there is a work around (but not a work around we are telling people), needs refinement, for now severity is normal ? and then based on the amount of work solution needs maybe priority can be changed

**Comment by andreievg** [comment]
Triage, maybe the refinement can determine when this is done ? We've had conversation about this area a few times, maybe that should be reflected in the priority

**Comment by mark-prins** [comment]
Note: the inventory adjustment reason has a `staleTime` set to 5 minutes, rather than the default of `0`

```
      staleTime: 5 * 60 * 1000,
```

**Comment by lache-melvin** [comment]
Closed by #4249
