### ISSUE TITLE
GAPS: Capture vaccine item variant volume requirements

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3917]
Part of epic #3662 

## Acceptance criteria
* [ ] Able to specify the type of vaccine storage which is used in a particular facility
* [ ] Able to specify the storage requirement of a vaccine variant, for `Primary` `Secondary` and `Tertiary`

## Describe the solution you'd like 🎁
Add custom field support for items
* add a column to the item table for `custom_data`
* include this column in sync
* extend the mSupply item import to include custom_data
* display custom field data in the item detail page
Add a custom field to the footrunner script used to create names for the vaccine storage type

### Additional context 💌

| User story  | B.2.7 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to specify the cold storage volume requirements per dose for **each presentation** of each type of vaccine
So that… | this volume can be taken into account when calculating cold storage space requirements

**Solution B.2.7**

The system will allow central users to specify individual vaccine volume requirements (in litres) on the Master Data product catalogue. 
This data is required to calculate the total cold storage capacity required per person per immunization program. 

| User story  | B.2.7.1 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to specify the cold storage volume requirements per dose for **each presentation** of each type of vaccine per Primary, Secondary and Tertiary packaging
So that… | the volume calculation is accurate when different forms of packaging are used to store the vaccines

**Solution B.2.7.1**

The system will allow central users to specify up to 3 levels of vaccine volume requirements (in litres) on the Master Data product catalogue to reflect the different forms of packaging used at different levels of the supply chain. 

| User story  | B.2.7.2 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | the appropriate form of packaging (Primary, Secondary, Tertiary) used by each facility to be captured
So that… | the volume calculation is accurate for each facility

**Solution B.2.7.2**

The system will allow facilities to specify the level of packaging they are using to store their vaccines. 
The facility users will be able to select one of the levels for their facility as defined by the central users in the Master Data product catalogue. 

**Extra context**

Example of WHO IGA item granularity: 

![image](https://github.com/user-attachments/assets/9b908ffc-f4f5-472e-bdf1-5a13a21b5461)

### Moneyworks Jobcode 🧰
`CCEIDEV`

**Comment by adamdewey** [comment]
There was an oversight in the requirements, User Story B.2.7.1 should read: 

| User story  | B.2.7.1 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to specify the cold storage volume requirements per dose for **each presentation of** each type of vaccine per Primary, Secondary and Tertiary packaging
So that… | the volume calculation is accurate when different forms of packaging are used to store the vaccines 

This likely requires the introduction of `Item variants` or a similar mechanism. 

Effectively we need a way to store preset Packsizes (+ associated data such as packaging) against items. 

But it doesn't necessarily need to affect stock management functionality.  

GAPS would be ok just storing down to the packsize granularity, but there would also be the possibility of storing down to the manufacturer granularity for more accurate stock management (currently in talks with one client who has requested this)

**Comment by craigdrown** [comment]
Just putting this out there - I don't think you should make a new table and link the barcode table to it - I think you should use the barcode table
<img width="340" alt="CleanShot 2024-08-26 at 20 41 47@2x" src="https://github.com/user-attachments/assets/10f07c0e-065b-4efa-bf95-2c0d863907f2">
All existing fields are relevant - just reused "spare_1" as "trade_name" and add new fields as needed.

**Comment by marthakeezy** [comment]
I have tested this as a part of V2.4.0 Release Testing - specifically in #5397

And I can still see packaging levels/types in the UI and able to save them

Moving to Done ✅
