### ISSUE TITLE
Add delete action to vaccine course within vaccine course detail view

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#4094]
There's no delete action on the [wireframe in epic issue](https://github.com/msupply-foundation/open-msupply/issues/3916), make sure that one is added and then hooked up
the spec says 'one or more vaccines' so the wireframe needs work: likely use a datatable with the delete checkbox / action

- [ ] Add delete button to remove vaccine course
- [ ] Add delete mutation to back end (will need to be soft delete)
- [ ] Add delete to graphql and front end api
- [ ] Prompt to warn people before deleting a vaccine course
- [ ] Show success or fail snack on success or fail

**Comment by adamdewey** [comment]
Might need some thought here..

Deleting is not a problem for GAPS but I think it could be for the digital vaccination card?

Because the immunization programs will also be used for modelling the digital vaccination card then I think we need to be careful about allowing deletion. 

Perhaps the delete option should be disabled if 1 or more patients has received a dose from the vaccine course?

**Comment by adamdewey** [comment]
Talking to team in meeting - if user soft deletes then it would be possible to retrieve by contacting support team. 

Could possibly add UI for un-delete but would probably not be worth it at this stage.

**Comment by adamdewey** [comment]
In the future, with the vaccination card we will be able to check to see if any patients have been enrolled in the program and prevent delete if necessary.
