### ISSUE TITLE
`Last Sync Attempt` date time is Tomorrow ( about 24 Hours ago)

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#4156]
## What went wrong? 😲

<img width="901" alt="Screenshot 2024-06-14 at 17 10 25" src="https://github.com/msupply-foundation/open-msupply/assets/117138852/2ade1edf-a4bc-47f2-a23c-b592da436e88">

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have two machines(Server and remote), Server’s date is 1 day ahead of the Remote
2. Setup mSupply Central Sever and Open-mSupply Central Server on the server computer
3. Put the cert files so that you can ascess the Central Server from remote
4. Go to server computer and see the Open-mSupply is running locally, shows right date and time
![Screenshot 2024-06-14 at 17 17 59](https://github.com/msupply-foundation/open-msupply/assets/117138852/214af1ca-3f38-4291-a62f-f07dfce8afa2)
5. Now try to access the Central Server form Remote machine via URL
6. Login and go to synchronisation Window
7. You will see the Last Sync attempt as `Tomorrow (24 hours ago)` (BUG)

## Your environment 🌱

- Open mSupply Version: v2.1.00
- Legacy mSupply Central Server Version: v7.16-00-dev9

- Platform: Windows

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Hi Santosh - can you please confirm, were you changing the timezone of the remote/central servers, or actually changing the system time?

**Comment by andreievg** [comment]
¯\_(ツ)_/¯

**Comment by lache-melvin** [comment]
As discussed in tester meeting - configuration issue rather than bug. This was a result of changing system time rather than time zone - if system time is incorrect, that could result in a lot of bigger issues (like ledger discrepancies!) so it is not something that we support.

Briefly mentioned if we need to show something other than the `ago` if time is in the future, but we handle time zones, so we never some have sync times that are in the future 🤷‍♀️
