### ISSUE TITLE
GAPS: Capture stock safety buffer for facilities

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4370]
## Describe the solution you'd like 🎁

- Add `months_understock` store pref to the store properties modal - see comment below

### Additional context 💌

| User story  | B.2.13 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to specify stock safety buffer values for each facility in months
So that… | our forecasting can use this to calculate the maximum amount of each type of vaccine that can be expected to be stored at each facility at any point during the year

**Solution B.2.13**

The system will provide a mechanism for central users to enter a figure to represent the stock safety buffer in months for each facility.

This will be the number of months to represent the supply that facilities keep in reserve in case of issues with deliveries.

The interval will apply to all commodities, not to individual types of vaccine.

---

_Note_: the wording has changed from the original user story in the design doc as UNICEF clarified that 

> "The values are assigned at the central level guided by the iSCM/EPI policy/Manual."

### Moneyworks Jobcode 🧰

`CCEIDEV`

**Comment by adamdewey** [comment]
There is an OG store setting that already captures this value - however we should group the supply interval value along with this safety buffer value (supply interval value doesn't exist in OG afaik)

We should display the values in OMS as non-editable so that it's easy for users to view without having to look in OG

**Comment by mark-prins** [comment]
Would that be the store pref for `Threshold for understock`?
Are you suggesting that we take the value for that, and display alongside a new facility property for 'supply interval', with the former as read-only?

**Comment by adamdewey** [comment]
> Would that be the store pref for Threshold for understock?

Yes that's the one!

> Are you suggesting that we take the value for that, and display alongside a new facility property for 'supply interval', with the former as read-only?

Either that or we create an OMS version too and don't bring across the OG one when it's finally time to port it across to OMS?

**Comment by mark-prins** [comment]
..or we create a new one and have the sync code (from OG) read the store pref and populate the new property if it's blank 🤔 

cool - thanks Adam, we can make something work 🙏

**Comment by lache-melvin** [comment]
the "Threshold for understock" is being synced from OG already `store_preference.months_understock`, being used for reports. Let's display this in the store properties modal as read only field.

Given store properties are just a JSON object on `name` at the moment, I think easiest to query/display the months_understock store pref (read only) separately, display that, then show the rest of the fields below (rather than trying to do anything tricky in sync, adding/overwriting name properties...)

Can be resolved whenever we start to port more of these prefs over to OMS central.

![Image](https://github.com/user-attachments/assets/1fe54ca0-5d05-4949-9906-708bad87a24a)

**Comment by lache-melvin** [comment]
Upon closer look, the existing 'months understock' store pref is on the store, rather than the name record, and so only exists for stores rather than facilities too. I thought it would be great to be able to reuse, but I think might cause more headaches than help...
We'll add another facility property, and ignore the store pref there. Mark says to call it a feature, you can independently configure the buffer value without messing up your ordering parameters!

**Comment by marthakeezy** [comment]
# 🧪 Testing

Tested as a part of V2.4.0 GAPS feature testing, also tested just now in `V2.4.0-RC6`

- [ ] You'll need to not have GAPS currently configured
  - [ ] This does raise the 'we need to handle adding more facility properties once the system is already configured' issue, but I reckon we cross that bridge when we get to it 😁 
- [ ] Initialise GAPS facility properties on OMS central (settings -> configuration -> intialise)
- [ ] Configure the stock safety buffer for a facility on a remote OMS site
- [ ] Log into that remote site and ensure the value has synced to it and is not editable

No issues found, working as expected - moving to Done ✅
