### ISSUE TITLE
Report filter doesn't filter if you type too fast

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#4464]
## What went wrong? 😲
The report filter doesn't correctly apply the text that was inputted if the user types/presses ok too fast

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Set up new reports in mSupply (download from reports repo)
2. Sync
3. Click on one of the reports
4. Type an item name really quickly and press Ok
5. See bug

## Your environment 🌱

- Open mSupply Version: 2.2
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
This is also could occur in some patient forms, but the effect is usually hidden by another confirmation modal, which introduced a delay.

Btw I think the issue is with 'how' we are using json form, but first of all the reason for debounce is explained here:

https://github.com/msupply-foundation/open-msupply/blob/199aa5e9341f7adb321b2d72c5cf6a166fc760f7/client/packages/programs/src/JsonForms/common/components/DebouncedTextInput.tsx#L18-L19

I think originally we introduced it here: https://github.com/msupply-foundation/open-msupply/pull/389, and then added some comments about performance, which looks like it's not the reason why it was added.

There is also some trickery with cacheing:

https://github.com/msupply-foundation/open-msupply/blob/199aa5e9341f7adb321b2d72c5cf6a166fc760f7/client/packages/programs/src/JsonForms/common/components/DebouncedTextInput.tsx#L26C4-L30C92

I think json form is meant to be rendered with 'data' being the initial state. But we have a couple of wrappers on top of it:

https://github.com/msupply-foundation/open-msupply/blob/cf45f5f7fc039b16a04787e1d8f1c10810c2dc7e/client/packages/programs/src/JsonForms/common/JsonForm.tsx#L118

https://github.com/msupply-foundation/open-msupply/blob/cf45f5f7fc039b16a04787e1d8f1c10810c2dc7e/client/packages/programs/src/JsonForms/common/JsonForm.tsx#L208

All of these will be re-evaluated on every key stroke, but I am still not sure how this would lead to huge performance issues. I think we would need to re-revert the debounce at some point and try to investigate what is cause the performance issue

**Comment by andreievg** [comment]
For now I think the only safe thing we can do is to add a prop to this component to not debounce, and use it in the argument form

**Comment by roxy-dao** [comment]
Closed in #4523
