### ISSUE TITLE
V2.2.0 Release Testing: Internal Orders

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#4621]
Tested on `V2.2RC5`

# Internal Orders

### Viewing Internal Orders

- [x] Navigate to the Replenishment menu -> Internal Orders
- [x] You will see a list of all existing Internal Orders
- [x] You can use the `Search by comment`  field to filter the list by the comments of the Internal Orders
- [ ] You can sort the list using the column headers.
- [ ] Tap the column header of the column that you want to sort. The column is sorted in ascending order.
- [ ] Tap the column header again and column will be sorted in the opposite order.

### Creating a new Internal Order

- [ ] Click on the `New Order` button (top right corner).
- [ ] A new window opens, inviting you to select a supplier
- [ ] Select a Supplier by pressing on their name. 
![Screenshot 2023-11-16 at 11 28 26 am](https://github.com/msupply-foundation/open-msupply/assets/115983430/1dddf5b5-f4e9-480c-a0c7-5665cb0216c2)
- [ ] Select a Supplier by pressing on their name and you will see a window like this:
![Screenshot 2023-11-16 at 11 39 09 am](https://github.com/msupply-foundation/open-msupply/assets/115983430/eb43be72-550e-4b27-8c4f-e7301185f517)

### Defining Maximum Month of Stock (Maximum MOS)

- [ ] Defining the Maximum MOS (Month of Stock) is critical to the calculation of the Suggested Quantity and you can change it
- [ ] This can be done before or after adding items to your order

### Adding a single item

- [ ] Tap on `Add Item` to add a single item to your order. A new window opens
<img width="1014" alt="Screenshot 2023-11-16 at 12 21 23 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/5b0acf2a-3e6f-4826-aa65-f6a038e9bb68">

- [ ] First select the item you want to add to your order. You can also type some or all of the item name (or code) to look for the specific item.
- [ ] Once item is selected you should see the following info:
- Item Code and Item Name
- Unit: the default unit used for this item (eg. Tablet, Vial)
- AMC: Average Monthly Consumption. How much stock your store uses each month on average (based on a configurable number of months, default is set to 3 months)
- Suggested Quantity: how much stock mSupply suggests that your order to reach your stock target quantity
Order quantity: the quantity of units that you request from your supplier
- [ ] You should also see the following charts:
- [ ] Stock distribution : In this chart you will see the following info
- The Target Quantity for the item. This is calculated as: Maximum MOS x AMC.
- Your current Stock on Hand (in grey)
- The suggested quantity calculated by mSupply
![Screenshot 2023-11-16 at 12 49 38 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/17b152bd-4ac8-4f65-9efb-3a8b8ec04cd3)
- [ ] Consumption History (monthly): this chart shows the monthly consumption up to 12 months in the past (in grey) and the current AMC (in orange)
![Screenshot 2023-11-16 at 12 50 31 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/63e21bd8-ab24-4c46-9e9a-24f17429be45)
- [ ] Stock Evolution: this chart shows you your stock level for the last 30 days and your projected inventory for the next 30 days. The projected stock will be updated based on your inputs in the Order quantity field
![Screenshot 2023-11-16 at 12 51 32 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/16d81c82-0bd6-4ce6-8a47-bab192e70b9b)

### Requesting a quantity in packs

- [ ] If the item which you have selected has a default pack size configured then you can see the documentation on [editing units ](https://docs.msupply.org.nz/items:adding_a_new_item#general_tab) for details then you see a few additional elements on the` Add item` window
- [ ] The new elements are:
- The default packsize 
- A switch to toggle between Units and Packs
- An input field for Requested packs
- [ ] When entering the requested quantity in the number of packs, you'll see the fields as above. The Requested packs input is enabled, and the Requested quantity is disabled, and automatically calculated for you.
- [ ] The reverse happens when you are entering by units
![Screenshot 2023-11-16 at 2 15 30 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/6f292312-0e61-4404-8818-3d765742a83f)

### Adding using a master list

- [ ] Tap on the Add from master list button
- [ ] Select a master list
- [ ] A dialog window opens asking you whether you want to add all of the items from this master list. Tap OK if you wish to proceed.
- [ ] All the items of the master list are now listed and if you had previously added a single item, it must add items that are not already there.
- [ ] You should be able to create orders from multiple master lists by repeating above actions with another master list

### Using Suggested quantities

- [ ] If you tap on the Use Suggested Quantities on the requisition header, mSupply should automatically copy the values in the Suggested Quantity column into the Requested Quantity column.
- [ ] You can always manually edit the order quantity for each by tapping on the order line.

### Printing an internal order

- [ ] Simply click the `Print` button which is on the top right of the page.
- [ ] PDF file is generated for you which will open in a new browser tab.
- [ ] This can be printed by clicking print or `Control + P` or `cmd + P` keys on keyboard.
- [ ] This will either show menu of possible reports for you to select from before creating a PDF. This will happen if there are more than one report defined for the `Requisition` report type.
- [ ] Create a PDF immediately, if there is only one report to select from.

### Sending an internal order

- [ ] To send the order to your supplier, tap on the Confirm Sent button (bottom right corner).
- [ ] A dialog window opens asking you whether you are sure to want to send the order. Tap on `OK` to proceed
- [ ] Status of your order should be now SENT and the order is no longer editable

### Approving Internal Orders

- [ ] Remote approval process
- [ ] it is possible to configure stores, so that requisitions require approval from specified users before they can be fulfilled. For a full description of this process refer to the mSupply[ Remote Authorisation](https://docs.msupply.org.nz/other_stuff:remote_authorisation) documentation.
- [ ] In the requesting store, enable the store pref `Include requisitions from this store in supplier's remote authorisation process`
- [ ] In the supplying store, enable the store preference `Use remote authorisation for response requisitions`
- [ ] When configured this way, the requesting store will see an additional column in the Internal Order list, showing the approval status.
- [ ] And when viewing a specific Internal Order, there are columns showing the approved quantity, approved number of packs and a comment entered by the approver, if there is one.
- [ ] Similarly, the supplying store will have an additional column in the requisition list view showing the approval status 
- [ ] And finally, a specific requisition will also have new columns, for the approved quantity and an approval comment, if one has been entered by the approver
- [ ] Local approval process
- [ ] In this option you can allow only certain users to change the status of an Internal order to `Sent`. To allow this ti user, they require permission `Can confirm Internal Order as Sent` to be enabled.
- [ ] To set the permission, edit the user within mSupply and change the tab to the `Open mSupply permission` tab shown below.
- [ ] Without this option checked, the user shouldn't be able to update the internal Order status to `sent` and the order is unable to be processed.
- [ ] On changing the status to `Sent` the user's details are added to the comment field; this can be seen when viewing the internal order in the details panel.
- [ ] Also shown to the remote approver in the remote authorisation web application if that is being used
- [ ] Inbound Shipments
- [ ]  This can be used to receive stock from suppliers(Supplier Invoice)
- [ ] All received goods should be recorded in mSupply either by manually creating an Inbound Shipment or working with an Inbound Shipment that has been created automatically as a result of a stock transfer from another store in your mSupply

**Comment by regotaina** [comment]
Continue testing on RC5
Desktop app

- [ ] You can sort the list using the column headers.
- [ ] Tap the column header of the column that you want to sort. The column is sorted in ascending order.
- [ ] Tap the column header again and column will be sorted in the opposite order.

### Creating a new Internal Order

- [ ] Click on the `New Order` button (top right corner).
- [ ] A new window opens, inviting you to select a supplier
- [ ] Select a Supplier by pressing on their name. 
![Screenshot 2023-11-16 at 11 28 26 am](https://github.com/msupply-foundation/open-msupply/assets/115983430/1dddf5b5-f4e9-480c-a0c7-5665cb0216c2)
- [ ] Select a Supplier by pressing on their name and you will see a window like this:
![Screenshot 2023-11-16 at 11 39 09 am](https://github.com/msupply-foundation/open-msupply/assets/115983430/eb43be72-550e-4b27-8c4f-e7301185f517)

### Defining Maximum Month of Stock (Maximum MOS)

- [ ] Defining the Maximum MOS (Month of Stock) is critical to the calculation of the Suggested Quantity and you can change it
- [ ] This can be done before or after adding items to your order

### Adding a single item

- [ ] Tap on `Add Item` to add a single item to your order. A new window opens
<img width="1014" alt="Screenshot 2023-11-16 at 12 21 23 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/5b0acf2a-3e6f-4826-aa65-f6a038e9bb68">

- [ ] First select the item you want to add to your order. You can also type some or all of the item name (or code) to look for the specific item.
- [ ] Once item is selected you should see the following info:
- Item Code and Item Name
- Unit: the default unit used for this item (eg. Tablet, Vial)
- AMC: Average Monthly Consumption. How much stock your store uses each month on average (based on a configurable number of months, default is set to 3 months)
- Suggested Quantity: how much stock mSupply suggests that your order to reach your stock target quantity
Order quantity: the quantity of units that you request from your supplier
- [ ] You should also see the following charts:
- [ ] Stock distribution : In this chart you will see the following info
- The Target Quantity for the item. This is calculated as: Maximum MOS x AMC.
- Your current Stock on Hand (in grey)
- The suggested quantity calculated by mSupply
![Screenshot 2023-11-16 at 12 49 38 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/17b152bd-4ac8-4f65-9efb-3a8b8ec04cd3)
- [ ] Consumption History (monthly): this chart shows the monthly consumption up to 12 months in the past (in grey) and the current AMC (in orange)
![Screenshot 2023-11-16 at 12 50 31 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/63e21bd8-ab24-4c46-9e9a-24f17429be45)
- [ ] Stock Evolution: this chart shows you your stock level for the last 30 days and your projected inventory for the next 30 days. The projected stock will be updated based on your inputs in the Order quantity field
![Screenshot 2023-11-16 at 12 51 32 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/16d81c82-0bd6-4ce6-8a47-bab192e70b9b)

### Requesting a quantity in packs

- [ ] If the item which you have selected has a default pack size configured then you can see the documentation on [editing units ](https://docs.msupply.org.nz/items:adding_a_new_item#general_tab) for details then you see a few additional elements on the` Add item` window
- [ ] The new elements are:
- The default packsize 
- A switch to toggle between Units and Packs
- An input field for Requested packs
- [ ] When entering the requested quantity in the number of packs, you'll see the fields as above. The Requested packs input is enabled, and the Requested quantity is disabled, and automatically calculated for you.
- [ ] The reverse happens when you are entering by units
![Screenshot 2023-11-16 at 2 15 30 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/6f292312-0e61-4404-8818-3d765742a83f)

### Adding using a master list

- [ ] Tap on the Add from master list button
- [ ] Select a master list
- [ ] A dialog window opens asking you whether you want to add all of the items from this master list. Tap OK if you wish to proceed.
- [ ] All the items of the master list are now listed and if you had previously added a single item, it must add items that are not already there.
- [ ] You should be able to create orders from multiple master lists by repeating above actions with another master list

### Using Suggested quantities

- [ ] If you tap on the Use Suggested Quantities on the requisition header, mSupply should automatically copy the values in the Suggested Quantity column into the Requested Quantity column.
- [ ] You can always manually edit the order quantity for each by tapping on the order line.

### Printing an internal order

- [ ] Simply click the `Print` button which is on the top right of the page.
- [ ] PDF file is generated for you which will open in a new browser tab.
- [ ] This can be printed by clicking print or `Control + P` or `cmd + P` keys on keyboard.
- [ ] This will either show menu of possible reports for you to select from before creating a PDF. This will happen if there are more than one report defined for the `Requisition` report type.
- [ ] Create a PDF immediately, if there is only one report to select from.

### Sending an internal order

- [ ] To send the order to your supplier, tap on the Confirm Sent button (bottom right corner).
- [ ] A dialog window opens asking you whether you are sure to want to send the order. Tap on `OK` to proceed
- [ ] Status of your order should be now SENT and the order is no longer editable

### Approving Internal Orders

- [ ] Remote approval process
- [ ] it is possible to configure stores, so that requisitions require approval from specified users before they can be fulfilled. For a full description of this process refer to the mSupply[ Remote Authorisation](https://docs.msupply.org.nz/other_stuff:remote_authorisation) documentation.
- [ ] In the requesting store, enable the store pref `Include requisitions from this store in supplier's remote authorisation process`
- [ ] In the supplying store, enable the store preference `Use remote authorisation for response requisitions`
- [ ] When configured this way, the requesting store will see an additional column in the Internal Order list, showing the approval status.
- [ ] And when viewing a specific Internal Order, there are columns showing the approved quantity, approved number of packs and a comment entered by the approver, if there is one.
- [ ] Similarly, the supplying store will have an additional column in the requisition list view showing the approval status 
- [ ] And finally, a specific requisition will also have new columns, for the approved quantity and an approval comment, if one has been entered by the approver
- [ ] Local approval process
- [ ] In this option you can allow only certain users to change the status of an Internal order to `Sent`. To allow this ti user, they require permission `Can confirm Internal Order as Sent` to be enabled.
- [ ] To set the permission, edit the user within mSupply and change the tab to the `Open mSupply permission` tab shown below.
- [ ] Without this option checked, the user shouldn't be able to update the internal Order status to `sent` and the order is unable to be processed.
- [ ] On changing the status to `Sent` the user's details are added to the comment field; this can be seen when viewing the internal order in the details panel.
- [ ] Also shown to the remote approver in the remote authorisation web application if that is being used
- [ ] Inbound Shipments
- [ ]  This can be used to receive stock from suppliers(Supplier Invoice)
- [ ] All received goods should be recorded in mSupply either by manually creating an Inbound Shipment or working with an Inbound Shipment that has been created automatically as a result of a stock transfer from another store in your mSupply

**Comment by regotaina** [comment]
@AnushaUp do you think the Remote authorisation part is currently being tested on the 'Remote authorisation' module?

thinking about avoiding double work, just curious :)

**Comment by AnushaUp** [comment]
@regotaina Yeah we can test it in  'Remote authorisation' module. If this issue is completed testing, can we move this one to done??
