### ISSUE TITLE
Toggling custom theme on and off refreshes page

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#4650]
## What went wrong? 😲
Toggling custom theme on and off seems to refresh the page even if no changes have been made! It's not a breaking bug but is kinda annoying?

https://github.com/user-attachments/assets/b91a44d9-6984-48b0-a7fd-1f9e6a813606

## Expected behaviour 🤔
Should only refresh if I press save?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Settings
2. Click on display settings
3. Toggle custom theme on and off

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform: current development

- Database type:

**Comment by mark-prins** [comment]
currently the 'disabled' state is when the toggle is off - a refresh would still be required when toggling from an enabled custom theme to a disabled state. We'd have to also track if there were changes to the theme to handle the case where users toggle on/off repeatedly. The custom theme implementation was a quick win to get a customisable and demo-able version out; I wouldn't want to spend long refining it at this stage.

side note: the refresh on theme change was required due to our structure and the RTL layout handling iirc. Just swapping the theme wasn't enough for changes to be applied.

**Comment by andreievg** [comment]
Nice catch @roxy-dao, but it's only us that use this, so i think we just close this issue for now
