### ISSUE TITLE
Prescription: Price is only calculated from the first line if multiple packsizes are selected.

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4764]
## What went wrong? 😲

![telegram-cloud-photo-size-1-5114005898967232095-y](https://github.com/user-attachments/assets/2504f169-7998-429f-8c50-73d825eafcae)

![telegram-cloud-photo-size-1-5114005898967232096-y](https://github.com/user-attachments/assets/cff56285-2886-4f18-a3ef-88c21a6951ca)

## Expected behaviour 🤔

Total Price should calculated correctly
If there's more than one `Unit Price` it should show `[multiple]` like other columns do

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Make sure you have an item in stock with different packsizes available and prices
2. Create a prescription for a patient and select stock from two different packsizes
3. Check the prices are calculated correctly.
4. Test with default prices lists and discount price lists in case this affects things

## Your environment 🌱

- Open mSupply Version: 2.2

**Comment by alainsussol** [comment]
# 🧪 Testing



- [ ] Make sure you have an item in stock with different packsizes available and prices
- [ ] Create a prescription for a patient and select stock from two different packsizes
- [ ] Check the prices are calculated correctly.
- [ ] Test with default prices lists and discount price lists in case this affects things

**Comment by alainsussol** [comment]
@jmbrunskill 

Hi James,

I assume, by default price list, you mean an item being part of master list that is a price list ? Am I right ?

I am not sure what is a discount list though ? Can you please pinpoint it to me ? Thanks :)

**Comment by jmbrunskill** [comment]
Sorry for the slow reply, there's a couple of new pricing changes in mSupply which I was part of implementing.

Don't think it will be impact but thought it wouldn't hurt to check...


> `Test with default prices lists and discount price lists in case this affects things`
> 
> I assume, by default price list, you mean an item being part of master list that is a price list ? Am I right ?

https://docs.msupply.org.nz/items:pricing?s[]=default&s[]=price&s[]=list#default_price_list

This is a special master list that applies a standardised price for items, even if they're not

> I am not sure what is a discount list though ? Can you please pinpoint it to me ? Thanks :)

https://docs.msupply.org.nz/items:pricing?s[]=default&s[]=price&s[]=list#discount_lists
This is a master list that applies a discount to internal orders /outbound shipments but no prescriptions.


Hopefully those docs help explain it.

**Comment by alainsussol** [comment]
@jmbrunskill 
Hi James,

Sorry I am just coming back to this today as I had not tested the default price list, Discount list the first time as I was dragged to more urgent things. I decided to also tried patient list.

My first question is the changes implemented in mSupply OG, are they also valid in omSupply ?

I am asking because omSupply seems to be using the default price list prices as sell price for prescriptions even though the same item is also present in the patient list. The docs seems to say that whenever an item is present in both master lists, the patient list price should prevails for prescription. 

Here are my price lists

Default price list
![Image](https://github.com/user-attachments/assets/e990170f-e53d-4921-8031-d0c75f8c6819)

Patient list 
![Image](https://github.com/user-attachments/assets/447ed081-f5ed-4f85-bac4-aec086c8b93d)

Discount list
![Image](https://github.com/user-attachments/assets/e6b0d762-574f-479c-99ac-f7b39e93fcb2)

Here is my stock that I have created on omsupply using a stocktake putting my own cost and sell price

![Image](https://github.com/user-attachments/assets/2ff31bbb-d331-4ecd-9afe-910c5da516a0)

Here is my prescription where instead of using the sell price of 7.00$ it charges $3.00/unit which corresponds to the price of the discount.

![Image](https://github.com/user-attachments/assets/960ad72a-d704-4742-a2d9-3a712da49592)

If the patient list is not yet implemented in omSupply, I think it is the right behaviour but if the patient list has been implemented then I think it should have used the price of 2.5$ instead of 3.00$

**Comment by jmbrunskill** [comment]
Thanks Alain, this is great!

>If the patient list is not yet implemented in omSupply, I think it is the right behaviour but if the patient list has been implemented then I think it should have used the price of 2.5$ instead of 3.00$

I think this is correct, patient price lists haven't been implemented in OMS yet.
@mark-prins Do we want to add this to dispensing work in future?

**Comment by mark-prins** [comment]
yes, good point. that's on the list of 'other dispensing functionality'. Am thinking to write up the carryover dispensing work when we get to the end of this release and see what's left
