### ISSUE TITLE
When migrating a finalised stocktake there's no finalised date

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4766]
## What went wrong? 😲

Coming from [this comment](https://github.com/msupply-foundation/open-msupply/issues/3910#issuecomment-2328282610). If you have a finalised stocktake in OG and then migrate to an omSupply site - the stocktake comes across correctly but the status looks weird with no finalised date:

![image](https://github.com/user-attachments/assets/52bb8ccb-0af5-4b4c-91c6-c80273c214a8)

## Expected behaviour 🤔
The stocktake statue would look better if there was a finalised date

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Steps to reproduce the behaviour:
1. First on mSupply-OG remote-site, create a stocktake, finalise and sync
2. Then convert to an open mSupply site
  1. reset hardware ID for the remote site
  2. initialise the new oms-site
3. In oms, the `fn` stocktake shows as finalised but does not have a finalised date

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Low severity, not blocking any workflows but would be quick to clean up :)

**Comment by alainsussol** [comment]
# 🧪 Testing



- [ ] Have store in OG site
- [ ] Do stocktake finalised
- [ ] Migrate store to OMS site
- [ ] Initialise/sync whichever 
- [ ] Go to just created stocktake and see finalised datetime

**Comment by alainsussol** [comment]
@roxy-dao 
Hi Roxy,

After migrating a store to omSupply, the Stocktakes creation dates are correct but the dates in the Stocktake date column are wrong. They are displayed one day earlier. Possibly a timezone problem similar to [#5247 ](https://github.com/msupply-foundation/open-msupply/issues/5247. If I change my timezone to NZ  on my tablet that creation date is one day later than when it was really created and the date of the stocktake is correct. The stockdate date is also one day earlier in the stocktake window. The same problem also happens when created new stocktake in omSupply so it has nothing to do with the migration itself. Because of that I have opened an a new issue: [#5387](https://github.com/msupply-foundation/open-msupply/issues/5387)
