### ISSUE TITLE
GAPS: Implement item variants: Item UI changes

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4789]
Part of epic #4362

## Is your feature request related to a problem? Please describe 👀
There are several aspects of the GAPS work which require item variant capabilities
For reference this is the full [item variant PRD](https://docs.google.com/document/d/1fRZslRohRGaZnUo13a2eKZjfO0DGWwXtIFsbEah7A4Y/edit#heading=h.hyld495fuxe5)

We won't need all aspects of that; but we will need the ability to create and edit and sync item variants.

The variants will need to have these properties for the GAPS work:

| Name | Type   | Reference |
|:------ |:------ |:---- |
| Volume (x3) | float | #3917 |
| Bundle items | reference to n item variants | #3923 |
| Temperature range | enum | #4368 |

## Describe the solution you'd like 🎁

See #5141

UI - on OMS central:

![image](https://github.com/user-attachments/assets/01bcdcb6-84cd-4caa-ad50-e1bb9e897d52)

### Handling stock

Done in separate issue: #5145

**Comment by adamdewey** [comment]
One other thing to note here is that GAPS would require item variants to be used during stock management so we know which item variant is currently taking up space within CCE...

Big change to standard stock management functionality!

Also worth mentioning that Craig suggests using barcode table which is basically doing the same thing as item variants - i.e. capturing products at the [GTIN level](https://www.gs1.org/standards/id-keys/gtin)

**Comment by lache-melvin** [comment]
- Add Variants tab to item page
- In `Inbound`/`Customer Return`, add item variant select dropdown column to each new stock line
  - Probably also needed in stocktake new batches/add new stock line via inventory adjustment
- In `View stock` add new field to show/edit the variant

**Comment by adamdewey** [comment]
Unto the breach! 

...

One thing to consider: there should be a hardcoded pack size for each item variant, so if choosing an item variant it wouldn't make sense to also be able to specify a pack size for the generic item (our current functionality)

**Comment by lache-melvin** [comment]
Hi Adam - is the configured pack size for each variant a definite requirement for GAPS?

In conversations with @mark-prins, we'd agreed that for this round of GAPS, item variant would only include item "metadata" for GAPS calculations at this stage (i.e. packaging dimensions, temperature range). Otherwise we'll keep impacts on the rest of the app to a minimum for now. 

Configuring pack size is still in the full Item Variant spec, but has a lot more UI implications, which require significant design investment - à la pack variants from early this year 😅 

If this raises functionality concerns, please do let us know ASAP! 🙏

**Comment by adamdewey** [comment]
Hey @lache-melvin - ah I see!

Hmm, actually I don't think pack size is strictly required at this stage. 

**What we do need is to have a** `volume per dose` **for each item variant.** 

(Originally I was thinking that the unit for vaccines should be `dose` and the pack size would represent the number of doses per vial, but now I've been convinced by Louisa that the unit should be `vial` and that we should have an additional dose number property.)

I was assuming the volume per item variant would be added as `volume per unit` so that it can be used for items other than vaccines, but that will mean for vaccines we also need to capture the dose number per item variant so we can make the calculation for volume per dose.

**Comment by lache-melvin** [comment]
Thanks for raising this Adam! Have just had a chat with Mark, this was the outcome:

We'll capture `doses per unit` on the item variant, and will do the volume per unit, volume per pack, and volume per secondary pack, as you say -- is this the equivalent of primary, secondary, tertiary? (Assuming this means we also need something to the tune of `packs per secondary pack`)

I think volume per dose can be derived from `volume per unit` / `doses per unit`, seeing as doses wouldn't be individually?

IMPORTANT TO NOTE: the `doses per unit` at the item _variant_ level will be for GAPS purposes ONLY. It's just additional metadata to help make your storage requirement calculations more accurate.

Doses per unit is captured against the **_item_** in mSupply, and this is what informs the amount of vaccine item dispensed per dose from the vaccine card.

We don't have budget to adapt vax card for variants at this stage, so we'll recommend setting up another item if they need to dispense from variants with different doses per unit. 

Hopefully one day we can wire these two up - same with pack size - just won't be in scope for now 🙏

**Comment by jmbrunskill** [comment]
With the additional changes from adding packaging_variants table, the UI could now look something like this (with proper components of course)

![image](https://github.com/user-attachments/assets/4940360c-e5b4-4036-8462-a8727508dca4)

It might not make sense to use a table for the packaging levels, but I think aligning the packsize and Volume Per Unit for each level is probably cleaner than having just 6 fields with a long label like `Primary Packaging Pack Size` and `Tertiary Packaging Volume Per Unit`


@mariyamsupply feel free to do an updated design! We'll work on off something a long these lines to start with...

**Comment by jmbrunskill** [comment]
NOTE: Hardcoded to 1 packaging variant per level and 3 levels (for now)

**Comment by mariyamsupply** [comment]
quickly mocked it up, tables look a bit misaligned. wondering what can be improved...

<img width="1024" alt="variants" src="https://github.com/user-attachments/assets/8f9725a4-82f6-4926-b20f-9da5392e8daa">

**Comment by jmbrunskill** [comment]
Nice! Thanks Mariya!

**Comment by adamdewey** [comment]
I think I saw somewhere on a screenshot some tiny text with something like "1 HepB vaccine is bundled with 5 syringes" to explain the ratio, which I think would be an easy UX win if can figure out somewhere to put it!

For packaging would there be space to use the terms "Primary", "Secondary", "Tertiary" instead of 1, 2, 3?

This would be easier to understand at a glance for people in the industry

**Comment by mark-prins** [comment]
yep - +1 for `primary` `secondary` `tertiary` thanks @adamdewey!
it's not clear from the mock up, the pack size and volume were to be editable for the variants, as per our discussion yesterday. Not sure how that's going to work / look? should the table have inputs?

**Comment by mariyamsupply** [comment]
Updated version



<img width="1024" alt="variants2" src="https://github.com/user-attachments/assets/51c8db8b-f4d0-490b-ae72-4cc457381c42">

**Comment by marthakeezy** [comment]
I have tested this as a part of V2.4.0 Release Testing - specifically in #5397

Moving to Done ✅
