### ISSUE TITLE
Vaccine card: customer return not created when changing this facility -> other

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4883]
## What went wrong? 😲

Can't reverse the prescription when changing to another facility 😢 

## Expected behaviour 🤔

If you check the `reverse prescription` toggle... it reverse!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to a vaccination that was `given` at this facility (that has a prescription created)
2. Change facility to `Other`
3. Toggle the `Revert existing stock transaction` ON
4. Save
5. BUG: Reopen - still shows prescription at the top of the vaccination, no customer return was created

## Context

I think this is from the change to allow `given` vaccinations with no associated stockline... stockline might need to be NullableUpdate now? Currently, if given == true and stockline == null, we keep the existing stockline!

## Your environment 🌱

- Open mSupply Version: 2.3 RC1
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
closed by #4887

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.6.0-build-test-3`

- [ ] Go to a vaccination that was given at this facility (that has a prescription created)
- [ ] Change facility to Other
- [ ] Toggle the Revert existing stock transaction ON
- [ ] Save
- [ ] prescription no longer shows at the top of the vaccination, customer return was created

ALSO
- [ ] Create vaccination at Other facility
- [ ] Enter for date in the past
- [ ] Set to given
- [ ] Ensure no toggle shows up to `record historic stock transaction`

**Comment by marthakeezy** [comment]
# 🧪 Testing



Retesting in `V2.6.1-RC4` since quite a few things changed since i was waiting for an RC :)

- [x] Go to a vaccination that was given at this facility (that has a prescription created)
- [ ] Change facility to Other
- [ ] Toggle the Revert existing stock transaction ON
- [ ] Save
- [ ] prescription no longer shows at the top of the vaccination, customer return was created

ALSO
- [ ] Create vaccination at Other facility
- [ ] Enter for date in the past
- [ ] Set to given
- [ ] Ensure no toggle shows up to `record historic stock transaction`
