### ISSUE TITLE
Clicking Ok & Next after fetching patient from central goes to new patient creation page

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5000]
## What went wrong? 😲

https://github.com/user-attachments/assets/e46664ec-3486-4cd0-81cf-057a23022e95

## Expected behaviour 🤔
Should redirect me to the patient that I fetched. (There is a workaround by clicking the downloaded patient in the row on search page does redirect you to correct patient...)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have patients belonging to a different store
2. Create new patient that has the name of an existing patient from another store
3. Download patient from search step
4. Click Ok & Next
5. See new patient creation page

## Your environment 🌱

- Open mSupply Version: 2.3.0-RC5
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
Same in #2068

**Comment by lache-melvin** [comment]
Also bumped into this today! Thought the getting redirected to the new patient page was part of the ~experience~, maybe it wanted me to enter a new code for the patient at this new facility, but turns out I created a duplicate patient 😅 

Not critical for release but would love to see this resolved, imagine it is a common mistake/confusion 🙏

**Comment by CarlosNZ** [comment]
So what I'm planning to do:

When downloading a patient, after getting the download confirmation, you will get directed to the added patient page -- there'll be no opportunity to create a new one at this point.

Also, I think it would help if the "OK" buttons had more informative messages about what they will do rather than just "OK & Next", e.g.

- The normal view (when the patient already exists)
![Screenshot 2024-11-07 at 3 37 50 PM](https://github.com/user-attachments/assets/7ea84049-1b88-495a-9fdd-d1b85f2841ca)

- Confirming intention to download remote patient
![Screenshot 2024-11-07 at 3 39 12 PM](https://github.com/user-attachments/assets/63dcbde1-8ec8-4775-9324-34197e11dce1)

- After download:
![Screenshot 2024-11-07 at 3 39 18 PM](https://github.com/user-attachments/assets/d02a8d4b-e766-4376-b720-a121aaf421cc)

**Comment by mark-prins** [comment]
the clearer button labelling is great - I think that'd be super helpful

**Comment by lache-melvin** [comment]
Sounds great Carl! Love it 🚀

**Comment by AnushaUp** [comment]
# 🧪 Testing

You'll need to create some patients on mSupply central (4D) belonging to a different store than the currently logged in one.

- [ ] Create "New Patient". On the "search results" steps, button should show "Create new" (which loads new patient input with the search details entered)
- [ ] New Patient => Search for patient that already exists locally. Results should show up in "Search results", and clicking on one takes you to that patient details page
- [ ] New Patient => Search for a patient that only exists on central server. Search results should show "Download" icon next to patient.
  - [ ] Click to download. Confirm fetch. Once downloaded, clicking "View patient" should take you to that patient's detail page. You shouldn't be able to create a new patient at this point

**Comment by AnushaUp** [comment]
PASSED✅
