### ISSUE TITLE
On save, create prescription (picked status)

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5266]
Hook in the with the `Ok` click of the JSON form modal, to create the prescription. Create it in `picked` status, so the stock movement is created, but more items could be added to the prescription if needed.

Ensure this only happens one (in future saves, prescription ID already exists, shouldn't create again)

**Comment by CarlosNZ** [comment]
Couple of possible approaches I think of.

1. As a plugin:   
  From: https://github.com/msupply-foundation/open-msupply/blob/develop/client/packages/plugins/README.md 
    > Adding a button to a toolbar of a detail view which performs an external action like looking up shipping details from an external API. The plugin is provided with details of the object being viewed (e.g. draft shipment object) and can use that data when performing actions.
  
    This seems like a good case for such a button, which would supercede the default "OK/Save" button on any form where it's defined. We'd still need to specify the configuration in the form schemas somehow (i.e. define that a plugin should be used, and which one). It's be good to do this without changing the structure of either the form schema or the UI schema too much, but possibly an additional field `actions` on the UI schema would be okay.
2. As an extended functionality of the form component itself. Since the functionality will be associated with a particular form element (in this case, creating a prescription when an ItemSelector element is present), it kind of makes sense to define the behaviour with the form component logic. And this way, we wouldn't need to change the structure of the schemas at all -- this would just be configured by additional `options` on the form element UI schema definition. For this case we'd need to create a new component anyway ("Item Selector"), as the item selection logic is too specific for the general-purpose "Select" component. So we'd be adding a new concept to each form component -- an "action" that can be hooked up to the main form submission button. Then on submit, the JSON Forms module would check through the components used for any exposed actions, and if they are configured, execute them.

Having written this out, I'm leaning towards option 2, as it seems to make sense that certain actions would be fairly tightly coupled to specific form elements. Plus, the "scaffolding" is already in place -- the library of JSON Forms components plus the core form functionality, so I don't think exposing additional "action" functionality to existing components would be a big job.

**Comment by CarlosNZ** [comment]
Regarding option 1 and option 2 -- I actually think that ultimately, most of the JSON Forms components should *be* plugins, as they're very case-specific.

The ones in the "common" folder are fairly generic, and can be kept in the core codebase, but I think it makes sense for the more specific ones to become plugins:
![Screenshot 2024-11-12 at 2 59 03 PM](https://github.com/user-attachments/assets/34b65c03-7759-442b-926f-53c7cd1c7d9a)

Now's probably not the time to do that, but just thought I'd mention it as it we can eventually do Option 1 AND Option 2, but starting with Option 2 for this case would be first step to making that work.

**Comment by lache-melvin** [comment]
Closed by #5581

**Comment by marthakeezy** [comment]
Tested in `V2.4.1-RC3` as a part of #5676 

Prescription gets created only once the encounter is saved (green pop-up on the lefthand side), navigating to the prescription you can see the status is **Picked**. Moving to Done as build test passed ✅
