### ISSUE TITLE
Negative Available Quantity

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5359]
## What went wrong? 😲

I noticed one of the items showed negative available quantity. Not sure yet how to reproduce, so attaching my database for troubleshooting purposes!

Details I can gather: 

- It was while adding an item from the screenshots
- It was for a prescription 31 under Williams, Kathyyy dated back to 01/01/2008
- Status is New
- I tried adding another item to the same prescription but could not recreate the negative available stock...

Screenshots -> [here](https://drive.google.com/drive/folders/1w9XRVAMlMzob0vxqQig6LHGbaL72qF1Y)
Database -> [here](https://mega.nz/file/wRp31SJK#-RPLysquB7AHi10z1s1928BUE7umCiwOt_AQ7BuLI8k)

## Expected behaviour 🤔

Available quantity should not be negative

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Unclear!

## Your environment 🌱

- Open mSupply Version: V2.3.2-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome browser

- Database type: SQLite3

**Comment by marthakeezy** [comment]
Leaving as a comment here after convo with James: I was able to issue 10 as a prescription for one of the items in 2018... Earliest transaction I have is Inbound Shipment of 5000 from 22/02/2024.

**Comment by jmbrunskill** [comment]
I'm going to declare this a non-issue :)

For the first issue, Stock was introduced after it was picked (historically) for that line.
The system is working correctly in this case, as you're not able to issue stock before it was introduced now, so it saying -2 is ok, the system treats it as if it was 0 and prevents you from issuing stock.

For the second issue
The problem is that there is an invalid stock out transaction which as been applied to the stock line available quantity.

<img width="420" alt="image" src="https://github.com/user-attachments/assets/8ca44e9c-f68e-4f1b-9603-747e4989dca2">

This transaction is deliberately excluded from the stock Movements by the  `number_of_packs > 0` filter.

```
 CREATE VIEW invoice_line_stock_movement AS 
    SELECT
<COLUMNS>
    FROM
        invoice_line
        JOIN item_link ON item_link.id = invoice_line.item_link_id
    WHERE
        number_of_packs > 0
        AND "type" IN ('STOCK_IN', 'STOCK_OUT');
```
I'm not 100% sure of the reason for this filter and if it could be removed, but I think it's clearly a datafile issue, as a STOCK_OUT line can't be negative in normal operation (as far as I am aware).

**Comment by jmbrunskill** [comment]
New issue raised, I think we're ok to release without this fix as it's migration related... 

https://github.com/msupply-foundation/open-msupply/issues/5368
