### ISSUE TITLE
Program Status does not get updated when Patient Status History entry is deleted

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5399]
## What went wrong? 😲

Spotted by @noel-yeldos 🥇 

Program Status does not get updated if the Patient Status History entry is deleted. 

https://github.com/user-attachments/assets/0573a5e1-8bd1-478c-a8e2-caa6dd1ccf66

## Expected behaviour 🤔

Column should be blank if the associated Patient History Status is deleted

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Patients
2. Ensure the Programs are setup & enabled in your testing store
3. Once a patient is selected, enrol them in a program
4. When enrolled, leave the patient status history blank -> you will see the column is blank
5. Now create a new patient status history entry -> the column should get updated to the corresponding status
6. And when you delete that entry, the column does not get updated - error!

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome browser

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Hey @marthakeezy - I'm going to close this one, would you mind raising this in the [programschemas](https://github.com/msupply-foundation/programschemas) instead - anything related to the forms in the program area is entirely configured there rather than OMS code. 

However, we don't have funding/focus on the programs area at the moment, so aren't likely to pick up these issues for the time being. Probably best not to spend too much testing capacity in that area? 🙏

**Comment by marthakeezy** [comment]
Done!
