### ISSUE TITLE
iSC/Cold chain/GAPS: Inconsistent error messages when importing duplicated assets

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5467]
## What went wrong? 😲

Scenario: I have 14 assets in my store, and I exported a list of them. I then imported that same list into omSupply to test what error messages I get. 

<img width="1134" alt="Screenshot 2024-11-19 at 2 41 56 PM" src="https://github.com/user-attachments/assets/3d34e6b0-face-43f9-b16a-b824b3b8ee2f">

Result: inconsistent error messaging. 

1. Even though the list of assets I am importing is identical to what I already have in my store, I only get the 'duplicated' warning for some?

<img width="1453" alt="Screenshot 2024-11-19 at 2 39 04 PM" src="https://github.com/user-attachments/assets/fce781dd-52d1-4580-bb46-3a12b7b76d49">

2. Even when importing the same asset with identical information, one is getting an error and another one doesn't

<img width="1454" alt="2" src="https://github.com/user-attachments/assets/5144e0e6-ee05-442a-a72e-34007dccbe37">

3. Should the system recognise the user is trying to upload identical assets and only upload one of them instead of both?

## Expected behaviour 🤔

1. The errors should be consistent
2. The errors should be consistent
3. It would make sense for omSupply to notify users their data has duplicated and offer to only upload one, if two assets are identical

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to cold chain -> equipment
2. Have a few assets set up (e.g. maybe 5 or 10 for testing - create both catalogue and non-catalogue types)
3. Export that list into a CSV file
4. Click Import -> upload the file you just downloaded
5. See error display inconsistent - even though you have _all_ the assets already existing in your store, you will only get the message for some

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser for Mac)

- Database type: SQLite3

**Comment by noel-yeldos** [comment]
@marthakeezy consulted with @jmbrunskill about this. Could I please have your db file and the export file to test with?

**Comment by marthakeezy** [comment]
Hey! I shared my DB earlier with Roxy for another issue, feel free to use this one -> https://mega.nz/fm/JFoGSBpK

Also shared with you via email

**Comment by noel-yeldos** [comment]
@marthakeezy @jmbrunskill as discussed, the issue seems to be more with the flow of how the errors appear rather than a bug. The error messages are layered and don't all show at once. The onus seems to be on the user to fix each error before proceeding to successful import.

Recommendations for ui:
- Some distinction between errors and warnings for user. It is not very obvious that you can still proceed with warnings (other than the ok button being clickable). 
- Change language for warnings displayed to user. Current language feels more dev facing rather than user facing
![Screenshot 2024-11-25 at 1 13 57 PM](https://github.com/user-attachments/assets/a75a0b2e-2d7d-49bd-a362-0b7784342d71)


@jmbrunskill do you want me to leave that line of code as 
``` if check_asset_number_exists(asset_number, connection)?.len() == 1 {``` 
OR
```if check_asset_number_exists(asset_number, connection)?.len() >= 1 {```

== 1 gives the below error messages
![Screenshot 2024-11-25 at 1 10 28 PM](https://github.com/user-attachments/assets/27554aed-2281-4f5f-903a-33349931ab1b)

>= 1 gives the below error messages
![Screenshot 2024-11-25 at 1 22 02 PM](https://github.com/user-attachments/assets/26af8510-af48-4066-8106-af7fe2102a60)

**Comment by marthakeezy** [comment]
Thanks for taking a look at this Noel! :) I raised an issue to update the docs here: https://github.com/msupply-foundation/msupply_docs/issues/121

**Comment by jmbrunskill** [comment]
> `>= 1` gives the below error messages ![Screenshot 2024-11-25 at 1 22 02 PM](https://private-user-images.githubusercontent.com/109483613/389328787-26af8510-af48-4066-8106-af7fe2102a60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDAyMDYsIm5iZiI6MTczMjQ5OTkwNiwicGF0aCI6Ii8xMDk0ODM2MTMvMzg5MzI4Nzg3LTI2YWY4NTEwLWFmNDgtNDA2Ni04MTA2LWFmN2ZlMjEwMmE2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwMTU4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2I1M2MwYmMxMzY5ZWNlMzYyOGRmYzFhM2MxYmU1ODM2MDU4M2E0ZTk2MzViMjhlNDEzYmQ3MGFjMDVhY2JiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.60P8BVTDX887eb_R4MD2zWk1PF2xRSP1tZgzywMCGF4)

This version is correct, thanks @noel-yeldos please create a PR for develop. It only matters if the user ends up with duplicate assetnumbers which shouldn't happen very often (only via sync)

**Comment by marthakeezy** [comment]
Build test passed, moving to Done ✅
