### ISSUE TITLE
Manual Inbound Shipment - default pack size not displayed when adding lines using "Add from a Master List" button

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#5561]
## What went wrong? 😲

possibly similar to https://github.com/msupply-foundation/open-msupply/pull/5558

While the system is picking up the default pack size when adding a line using the "Add an item" button, it does not do the same when adding the same item but using the "Add from a master list" button: 

**Add an item button**

Default pack size (20) is automatically displayed

![Screenshot 2024-11-26 at 12 03 33 PM](https://github.com/user-attachments/assets/b031110b-a526-4dd7-883d-03c100ef840a)

**Add from a master list**

Pack size is showing 1 while it should 20

![Screenshot 2024-11-26 at 12 06 15 PM](https://github.com/user-attachments/assets/289055c9-8f5c-47c4-9cbf-06811d4c2c97)

## Expected behaviour 🤔

See above
## How to Reproduce 🔨

See above

## Your environment 🌱

- Open mSupply Version: 2.3.02
- Platform: browser (chrome)

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.5.0`

- [ ] Go to Replenishments -> Inbound Shipments
- [ ] Click on existing shipment or create a new one
- [ ] Click add from master list button
- [ ] Select a list and add items
- [ ] Check to see that pack size is using item default rather than setting to 1 (Note some packs have a default size of 1)
- [ ] Click on item to see that pack size displayed matches that from list view
