### ISSUE TITLE
Remove docs links from `mapRoute`

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5685]
## The suggestion

We moved the link to our docs to the `Help` page, so it always links to the introduction page. This makes the `docs` field on RouteMapping redundant:

https://github.com/msupply-foundation/open-msupply/blob/develop/client/packages/common/src/utils/environment/EnvUtils.ts#L16

### Why should we invest time in this?

We should remove to reduce confusion/unnecessary noise.

### Are there any risks associated with this change?

No, not used, just need to update Help page User Guide section, to get the docs introduction page differently... can probably just add `/introduction` to the `ExternalURL.PublicDocs`?

https://github.com/msupply-foundation/open-msupply/blob/895b747008119b7ee170dd4e1143ac97abef7fee/client/packages/host/src/Admin/UserGuide.tsx#L12-L15

### How much effort is required?

1 hour

**Comment by mark-prins** [comment]
I was hoping to retain the docs context - in the spec there's this line: 'The docs link currently takes you to the appropriate page - carry this behaviour through, so that the offline and online versions both link you to the correct section'

Mariya wanted to have the help page show the offline version of the docs page, with a few additional bits added - the feedback / request form and a link to the online version. If we do implement that ( and I'm aware that this request has come in after the sprint has started! ) then a context-sensitive page would be possible and desirable.

**Comment by lache-melvin** [comment]
Ah sorry, maybe I misunderstood - in the PRD: `Rename the Docs link to Help, create a new page which this links to.`

I thought this meant - no more docs link the App Drawer, but a link to the Help page. So the help page has a link to the docs, but wouldn't know the context of where you navigated from before.

Are you saying it should be:
- App Drawer has Help link (to help page, with online and offline docs links)
- App Drawer also has User Guide link, which works as `Docs` link does now?

**Comment by mark-prins** [comment]
No sorry - I'm still not being clear. this might be an IRL discussion!

Yes to this: no more docs link the App Drawer, but a link to the Help page. 

And then the help page has a link to the docs which does know the context. Yes, I'm making this difficult.
Following on though: @mariyamsupply prefers a version of the help page which displays the offline docs page, with the contact form link added to it. In this case, we can show the context appropriate offline docs page, and a general link to the online docs. maybe?

**Comment by lache-melvin** [comment]
IRL discussion happened - will make an issue for the next steps for the help/docs page, and close this one 🙏
