### ISSUE TITLE
XOF Currency

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5777]
Mali uses XOF (West African CFA franc). 

Symbol: CFA
Precision: 0
Rest same as euro

**Comment by lache-melvin** [comment]
You can use this PR as a reference: https://github.com/msupply-foundation/open-msupply/pull/4920

**Comment by mark-prins** [comment]
Please use `XOF` as the currency symbol - that's what CIV were using and this is the ISO symbol for the West African franc

Can you also add
* XAF
* CDF

while doing this change? There's two CFA francs, one is XOF and one XAF and we're likely to need both! Also the DRC uses CDF 🙏

**Comment by zachariah-at-msupply** [comment]
Oh wait I didn't see Mark's comment until now, I'll add those currencies too.

**Comment by roxy-dao** [comment]
Fixed in #https://github.com/msupply-foundation/open-msupply/pull/5786

**Comment by marthakeezy** [comment]
# 🧪 Testing



`Testing in V2.4.2-RC1`

- [ ] In 4D msupply navigator go to special>stores>select the store you want>preferences>tick "Store: able to issue in foreign currency".
- [ ] Log in to that store in open mSupply and go to distribution>outbound shipment.
- [ ] Create a new outbound shipment to PF0-15 (or any other thing that's not a store).
- [ ] Add an item to that shipment, of something that you have some stock of, and put a pack qty issued in that column. Ideally, add an item that has a a price with two digits afteer the decimal place: e.g. $2.55 or similar (that way you can test the precision of the rounding)
- [ ] Click ok to get back to the page you can add medecines from, and click more in the top right corner.
- [ ] Scroll down the side bar that opens up and edit the 'Foreign Currency' field.
- [ ] Change the currency to XOF, and observe that
        1. the unit is XOF
        2. the price is rounded to 0 dp
- [ ] Change the currency to X**A**F, and observe that
        1. the unit is X**A**F
        2. the price is rounded to 0 dp
- [ ] Change the currency to CDF, and observe that
        1. the unit is CF
        2. the price is rounded to 2 dp

**Comment by marthakeezy** [comment]
Going off testing steps above, noticed the following: 

`XOF & XAF Currency`

1. When clicking on an item added to the Outbound Shipment, FC Sell Price is not set to 0 decimal points - also there seems to be an issue of showing 5+ decimal points - possibly need to be rounded and shown as 2-3dp? Or 0?

<img width="1062" alt="2" src="https://github.com/user-attachments/assets/6c452fba-17e3-41f4-8a99-0385b1015eb4" />

<img width="1035" alt="5" src="https://github.com/user-attachments/assets/d2b4d86e-33df-4941-aea4-941e0221f380" />

2. Something odd happens when adding service charges - total in $ dollars is correct (e.g. $1454.56 + $50 = $1504.46) but XOF gains extra from somewhere? The new total is XOF1533.00 - this is happening for XAF and CDF as well

<img width="318" alt="4" src="https://github.com/user-attachments/assets/1d2ad883-45be-4093-992f-29cccf61c106" />

![6](https://github.com/user-attachments/assets/3ec44513-e54d-4140-91dd-8be64f583fbc)

**Comment by marthakeezy** [comment]
Raised #5793 for number 2 above

**Comment by marthakeezy** [comment]
Raised #5795 for number 1 above

**Comment by marthakeezy** [comment]
Apart from 2 bugs above, the rest looks good - passing the build test considering we are on a time crunch and checked with Roxy re: this. Moving ✅
