### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#704]
## Original Description ##

Some way of migrating databases when installing. The current method of deleting a database and creating anew then syncing the entire database from the central server isn't sustainable long term

## Break down ##

There was a discussion in this issue, followed up by a [KDD](https://github.com/openmsupply/open-msupply/blob/KDD-for-migrations/decisions/migrations.md).

* [x] 1. Add manual migrations mechanism 
* [x] 2. Add template migration examples and doc
* [ ] 3. Add some protection when migration fails (transaction etc, how does this work in mobile?)
* [ ] 4. Use manual migration mechanism for existing migrations (can carry over, maybe not required)
* [ ] 5. Add mechanism for `reverting` migration https://github.com/openmsupply/open-msupply/pull/722#discussion_r998951730 (can carry over)
* [ ] 6.  Suggest strategy for progress indication based on this comment: https://github.com/openmsupply/open-msupply/pull/722#discussion_r998949798 (can carry over)

## Others

https://github.com/openmsupply/open-msupply/pull/848#issuecomment-1341490752

### Integration test

It would be great to have the ability to test migrations on live data file (annonymised). There is a challenge in validating that migrations are indeed correct, either with sanity check (which would require logic to be written and probably tested) or something like a data diff, the latter might be a good option to go with. If we use automated github actions for this it would be more `available` for tester and more likely to be looked at.

Unforeseen data variations can cause migrations to fail, hard to put those in tests. That is absolutely true, not sure if we can protect against those, but if they do happen, having tests in migrations can help replicate the issue (by adding more test variations) and can protect from regression when those are fixed

**Comment by andreievg** [comment]
## Requirements

1. Update schema without re-initialising database
2. Migrate data
   a. Before and/or after schema update
   b. Without schema update (just data migration)
3. Do above only for the migrations that are applicable to from current database version to current app version (don't re-run old migrations)
4. Record migration results
5. Easy way to explore full schema (all of the migrations applied, for a particular version)
6. Test data migrations
7. Should work with RC versions
8. (maybe) Consolidate common sql for PG/Sqlite (we have quite a few duplicate sql statements)
9. (maybe) Use strongly typed diesel db if possible, for data migrations

## Examples/Extra

### 2.a 

There might be a need to do multiple schema and data updates within one version upgrade. For example if a required field is added that needs to be populated with some value derived from existing database values, we would want to:
* add schema without the constraint
* add the values 
* add the constraint

Another example is when sync buffer was consolidated:
* Add new sync buffer
* Copy rows from remote and central to the new sync buffer (see proposed solution, that touches on `9.`)
* Remove old sync buffer

Above can also be done by keeping existing sync buffer in memory than doing one schema migration with adding and removing sync buffer then populating new sync buffer from memory. 

I think it's better to keep migrations flexible, without a particular pattern of operation sequence.

### 2.b

If we add a new field/table in central and remote is not up to date, the field/table will still be synced and recorded in sync buffer. And when we update to a new version of remote that has this new field/table we can just crawl through sync buffer and try to re-integrate this new field/table. This avoids needing to re-sync this info, and we can avoid implementing this mechanism

Remote data should be safe with above example, as central shouldn't be updating foreign data.

### 4.

General data about migration result should be logged for debugging purposes, and on migration failure we can't guarantee correct behaviour of the app, so we would need to either disable server and not allow it to start again or revert to previous data version and inform the admin/user that app can be downgraded. 

I think ability to revert to previous version (on failure) allows for system to be available to the users in timely manner, in case errors in migration occur.

### 6.

This could be tricky especially if we want to use diesel db strong typing. I think this in necessary and very important, we've had some major failures in the past with data migrations.

### 7.

Say we are on version 1.01, and are working on version 1.02, before deployment we should be able to:
* Make an RC version, say 1.02-RC1
* Test upgrade of 1.01 data file to 1.02-RC1 (just by replacing binary)
* RC versions should not be upgradable, if you open RC version and there is a version mismatch then user should be warned that version are incompatible (this is to avoid additions to migrations that won't run or won't be tested)
* When we happy with 1.02, it's released and 1.01 would be upgradable to 1.02-RC1

### 9.

Since our diesel type from previous version wont' be compatible with new version we might need to resolve to using raw sql statements to migrate data, I would prefer if we copy and paste data types from pre migrated version to do data migrations (see example in proposed solutions)

## Proposed solution

I think out of the box diesel schema migrations are not flexible enough to support the above. I suggest we use visitor pattern for migrations. Since schema migrations are just sql statements, we can run raw sql to accomplish the task. Migration should run within transaction to allow reverting upgrade as per **4**. Visitor implementation should be simple, it should be able to tell the caller that this migration is need and have a method that runs migration (which just take in connection). The driver of migrations can set the version after each successful migration.

### migration_driver example

```rust
fn migrate(con: &StorageConnection, version: Option<u32>) -> anyhow::Error {
    // This method can be called in tests with required version, None for version would mean it will update to current version
    let version = version.unwrap_or(VERSION)

    let migrations: Vec<Box<dyn Migration>> = vec![V1_02, V1_03];

    // if version(con) is above VERSION, warn user that version mismatch

    for migration in migrations {
        let current_db_version = version(con); // Version is stored in key value store
        let version = migration.version();
        if current_db_version < version {
            let result = con.tx(|_| {
                migration.migrate(con)?;
                increment_version(con, version); // Version is stored in key value store
            });
            // Do something with result
        }
    }
    increment_version(con, from_text_version(version)); // Current version
}
```

### V1_02 example

```rust

const prepare = r#"
   CREATE TABLE buffer (
    # something here
   )
"#;

const finalised = r#"
   DELETE TABLE remote_buffer;
   DELETE TABLE central_buffer;
"#;

// Since this won't exist in code base anymore, have to copy paste from deleted, similar if table definitions were changed
table! {
    remote_buffer (id) {
        id -> Text,
        thing -> Nullable<Text>,
    }
}
// Since this won't exist in code base anymore, have to copy paste from deleted, similar if table definitions were changed
table! {
    central_buffer (id) {
        id -> Text,
        thing -> Nullable<Text>,
    }
}
// Since this won't exist in code base anymore, have to copy paste from deleted, similar if table definitions were changed
#[derive(Clone, Queryable, Insertable, AsChangeset, Debug, PartialEq)]
#[table_name = "remote_buffer"]
pub struct RemoteBuffer {
    pub id: String,
    pub thing: Option<String>,
}
// Since this won't exist in code base anymore, have to copy paste from deleted, similar if table definitions were changed
#[derive(Clone, Queryable, Insertable, AsChangeset, Debug, PartialEq)]
#[table_name = "central_buffer"]
pub struct RemoteBuffer {
    pub id: String,
    pub thing: Option<String>,
}


struct V1_02;

impl Migration for V1_02 {
  fn version() -> u32 {
    from_text_version("1.03.01")
  }

  fn migrate(connection: &StorageConnection) -> anyhow::Error {
    sql_query(&prepare).execute(&connection)?;
    
   let remote: Vec<RemoteBuffer> =  remote_buffer::dsl.load(connection);
   let central: Vec<RemoteBuffer> =  remote_buffer::dsl.load(connection);
   // Since buffer repository will now exist in code base, can use it from repository
   BufferRepository::new(connection).upsert_many(remote.iter().map(/* translate to new Buffer */));
   BufferRepository::new(connection).upsert_many(central.iter().map(/* translate to new Buffer */));

    sql_query(&finalised).execute(&connection)?;
  }
}

#[test]
fn test() {
   let con = init_database("test");
   migrate(con, V1_01.version());

   diesel::insert_into(remote_buffer::dsl::remote_buffer).values(&RemoteBuffer {
    // Some mock values
   }).execute(&con)?;

   diesel::insert_into(central_buffer::dsl::central_buffer).values(&CentralBuffer {
    // Some mock values
   }).execute(&con)?;

   migrate(con, V1_02.version());

   assert_eq!(BufferRepository::new(connection).all(), vec![Buffer {/* some mock values */}, Buffer {/* some mock values */}];
}
```

Above should explain how most of the requirements are met, `8.` can be met using cfg flags for pg/sqlite if they differ. 

It should be very easy to navigate to any given migration if they are located in their own file or directory. 

`5.` can be dealt with by exporting to `schema spy` for each version, and hosting on github actions.
`4.` As for logging, can be logged to files for now (but we do want further issue/discussion about logging) {insert issue here}

### Mobile considerations

We want to display an error somehow if migration fails, not actually sure what happens right now if there is say database error during startup. Could potentially have another schema `migration`, and another table to record migration results, similar to sync status.

**Comment by jmbrunskill** [comment]
@andreievg Are you suggesting running a combination of the current diesel migrations and these new rust based migrations?
How would adding a new table be handled in this approach, let's say the `Tender` related tables needed for HSH?

I think the proposed approach while testable (which is nice, will potentially create a lot more overhead for creating simple  migrations such as adding a new table). I'd like to see a bit more justification as to why this is needed (I don't know all the history with these)

I'll also make the comment  that just because something is testable doesn't mean it actually would be tested well...

Do you expect all the migration tests to be run before every PR? Or would they be behind a feature flag?

I wonder if we should compare pros and cons against other ideas such as testing migrations with integration tests?
Maybe written up as KDD?

**Comment by andreievg** [comment]
>  Are you suggesting running a combination of the current diesel migrations and these new rust based migrations?

Nope just the rust based migrations, replacing existing diesel migrations

> How would adding a new table be handled in this approach, let's say the Tender related tables needed for HSH?

**migration_driver**
```rust
// increase overall version
const VERSION: &'static str = "1.05.00";
// add this line to visitors, wouldn't be able to miss it since V1_05 would be pub(crate) and will have compilation warning if not used
   V1_05
```
new file **V1_05.rs**
```rust
impl Migration for V1_05 {
  fn version() -> u32 {
    from_text_version("1.05.00")
  }

  fn migrate(connection: &StorageConnection) -> anyhow::Error {
    sql_query(r#"
        CREATE NEW TABLE(
            # table here
        )
    "#).execute(&connection)?;
  }
}
```

no data or schema change, no tests needed

can do an extra check in driver so that we don't forget to increment VERSION number.

> will potentially create a lot more overhead for creating simple migrations such as adding a new table

Is this still true, given the above ? (also this allow common migrations, and trickier migration when only tiny part of the migration is different between pg and sqlite)

> I'll also make the comment that just because something is testable doesn't mean it actually would be tested well...

Hmm that's an overall comment about test right ? not specific to this ? I only agree about one part of that statement, that tests should be well written. And I've already experience soo much benefit of unit tests we've written (however, not all of the test we've written have been valuable.. yet)

> Do you expect all the migration tests to be run before every PR? Or would they be behind a feature flag?

I think they can run like unit tests, I can't see them taking any longer then a normal test we have that uses `setup_all`.

> I wonder if we should compare pros and cons against other ideas such as testing migrations with integration tests?
Maybe written up as KDD?

Sure I can do KDD, although I don't have any other solutions. I couldn't figure out how to use db diesel in combination with data migration. 

How would you test this with integration test ? I can see it being very complex, you would need to run older version of the app with some predefined data, then switch to newer version of the app and test data correctness ? (and do this for all of the migration version). And then if you do get an error, to replicate it you would need to do a lot of manual work to figure out where things fail ?

Will try to do KDD tomorrow.

> I'd like to see a bit more justification as to why this is needed (I don't know all the history with these)

Main justification is in the requirements, need to do data migrations, and we had issues with data migrations in mSupply (could they have been caught with tests ? maybe, but in my view maybe is better than "no because there is no tests"). Btw [here is migration code in mSupply ](https://github.com/sussol/msupply/blob/master/Project/Sources/Methods/startup_update_version.4dm)

**Comment by jmbrunskill** [comment]
> Hmm that's an overall comment about test right ? not specific to this ? I only agree about one part of that statement, that tests should be well written. And I've already experience soo much benefit of unit tests we've written (however, not all of the test we've written have been valuable.. yet)

Fair call! Wasn't a clearly thought out statement.
I'll talk to you in person to hear the war stories, but I was also wanting to understand examples of what has gone wrong in the past so I can more easily evaluate how this approach might help. 

My experience is that migrations have hardly ever been problematic, but where I've seen issues has often been with things like database locks due to production workloads being on the database while migrating, data migration sizes being too large causing long transaction rollbacks, and unexpected data situations which (I uncharitably conjectured) wouldn't have been thought about in tests either. 

This might be quite a different for mSupply though.
If migrations are complex then I can definitely see value in the approach.

> Is this still true, given the above ?
Thanks! I think you've shown that the code wouldn't be too complicated for simple cases. IMO it's still more involved than just throwing a sql query in a file but given the advantages for testing, ability to run rust code if needed, etc I'm pretty much convinced.

> (also this allow common migrations, and trickier migration when only tiny part of the migration is different between pg and sqlite)

Good point!

>How would you test this with integration test ? I can see it being very complex, you would need to run older version of the app with some predefined data, then switch to newer version of the app and test data correctness ? (and do this for all of the migration version). And then if you do get an error, to replicate it you would need to do a lot of manual work to figure out where things fail ?

I was thinking of something like a github actions job that could run migrations on anonymised copies of production databases.
Load database file, start app, check that migrations successfully completed, run sanity checks relevant for the version you are testing.
https://spawn.cc/ has a tool to help with this kind of thing (not saying we should use itm this is just as an example of the approach)
It would allow testing on fullsized databases, rather than a small dataset more suited to a unit test.

With this approach we could potentially test the migrations against a very close approximation of the real data the code will interactive with in production. We'd only need to test against database versions we have running in production, or are targeted to get the update.

Not saying this would be trivial to setup though. It would be a lot more work than what you're proposing which is a **big** downside. 

>Btw [here is migration code in mSupply](https://github.com/sussol/msupply/blob/master/Project/Sources/Methods/startup_update_version.4dm)

Ok that is certainly scary!

> Will try to do KDD tomorrow.

I don't think you need to rush into this, but thought it was worth considering.
It could be a good tool to summarise our thinking at the time and gives us something to point at when we asks why we made a custom migrations tool in the future.

**Comment by andreievg** [comment]
> I'll talk to you in person to hear the war stories, but I was also wanting to understand examples of what has gone wrong in the past so I can more easily evaluate how this approach might help.

I am not sure if I have concrete examples, can talk about it. 

The other thing that I didn't mention, without test how would you validate that your data migration works ? Doing it manually ? (wouldn't it be better to write a test, and if framework is there it should be pretty easy). And if we get conjured conjectures that require a fix, how would one go about fixing it ? (I would assume adding test case with that particular data set, also during this sort of fixes we have to be careful not regress, and existing original test would be helpful)

> but where I've seen issues has often been with things like database locks due to production workloads being on the database while migrating

Oooh, oki, will make sure to add that as requirement, that migrations should run in isolation from any other production operations

> data migration sizes being too large causing long transaction rollbacks

It sounds like at the very least, we need good feedback to the user about migration progress. I'll also add a point about possible back-up followed by migration vs transaction/rollback.

Thanks for those few points from your experience.

I wonder what an alternative would be to my comment ?:
```
Sure I can do KDD, although I don't have any other solutions. I couldn't figure out how to use db diesel in combination with data migration.
```
Raw sql data migrations ? What if they are a bit more complex than just default value or simple translation of a values ?

I like the idea of some sort of automated test against production data files. I think the biggest challenge would be writing sanity checks (as you can't just do mock data comparisons you would need to add logical validations, which would also need to be tested ?). Either way I think strategy for production data files migrations need to be noted, certainly need a strategy.

> I don't think you need to rush into this, but thought it was worth considering.

This needs to be implemented next week, so would be good to have clarity before then.

**Comment by andreievg** [comment]
KDDid it https://github.com/openmsupply/open-msupply/pull/722

**Comment by mark-prins** [comment]
@andreievg should we keep this one open? Seems to me that migrations are working nicely, and we have the kdd done too

**Comment by Chris-Petty** [comment]
@mark-prins @andreievg seems done aye?
